### PR TITLE
Remove old scripts

### PR DESCRIPTION
**Pull request by mauricioszabo**
Removing old build, snapshots, and bootstrap scripts now that we're using electron-builder

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
See now this is bloat, 33K+ lines!

Lets get rid of it all, Love it!

**Review by confused-Techie — APPROVED** [review]
See now this is bloat, 33K+ lines!

Lets get rid of it all, Love it!

**Comment by DeeDeeG** [comment]
I used the old script/build to troubleshoot an issue with the benchmark mode removal.

Hmmmm.

Maybe I can manually restore it in my local workspace (local project dir) while I'm working, and just have it as un-tracked files.

_(I don't really understand the yarn workflow that well.)_

My two cents. I still think this can be removed if most are in favor of it. Not trying to slow progress.

**Comment by Sertonix** [comment]
I suggest to also make these changes: #119

**Review by confused-Techie — APPROVED** [review]
Gotta say, I think this is the most passing tests I've seen in quite some time.

Let's get this merged

**Pull request merged**
