### PR TITLE
Rebranding to Pulsar - Icons and Logos

### PR DESCRIPTION
**Pull request by mauricioszabo**
image

### CODE REVIEW

**Comment by Daeraxa** [comment]
Question about the logo location ([packages/about/lib/components/atom-logo.js](https://github.com/pulsar-edit/pulsar/pull/173/files#diff-10c91dbea9ad34f221b0fe8ccca09dc0f3f0ca08d83562b2a306d129b18949c1)) is there nowhere more central we can use so that it can be referenced by other packages or the app without having to duplicate the resource?
There was a (short) conversation on [Discord](https://discord.com/channels/992103415163396136/992103415163396139/1044252243496534017) about it.

**Comment by Spiker985** [comment]
We should also (if we have it) add a banner to the README.md

**Comment by confused-Techie** [comment]
This overall looks great to me, although do we want to have any consideration to generating png's at the different sizes that have been removed? Would those be useful, or were we essentially not using them.

Or maybe it's better for us to wait on having all the right sizes until we have a final icon, and we just merge this one, so that we have something for now?

Because if it's the latter I say lets get it merged

**Comment by Spiker985** [comment]
I thought that I saw the largest file being 2048x2048 which is the largest file we had before if I'm not mistaken.

I wrote something to generate scaled images before, so we should just be able to generate the scaled down images, and recreate the `icns` files, the individual `png`s and the `ico`s

**Review by confused-Techie — APPROVED** [review]
@Spiker985 you're right, I missed the large icon.

In that case this looks great to me, and I'll happily merge it as long as it's complete

**Review by Spiker985 — APPROVED** [review]
This should be fine for an initial - this will evolve with our app styling choices anyway

**Comment by confused-Techie** [comment]
With two approvals I'll go ahead and merge this one, if needed a PR can always be made later to adjust these.

**Pull request merged**
