### PR TITLE
ppm: Update submodule to de6a852bd101e388b61fe67b5

### PR DESCRIPTION
**Pull request by DeeDeeG**
## How to do this kind of update:

When the changes you want are live at the default branch of ppm repo (https://github.com/pulsar-edit/ppm), run the following command in the root of the core repo to update the ppm submodule in the core repo:

`git submodule update --remote ppm`.

## Brief Summary of Changes

Includes a lot of decaf work from multiple contributors, a dependency bump, a small code refactor, a Windows postinstall script fix, and switching to our fork of npm 6 that includes node-gyp 9.x.

Also: Skip fetching updates for packages with repository `https://github.com/pulsar-edit/pulsar`, since these should be bundled packages, which we don't publish updates for on the package registry anymore, and for which we wish to save the API backend some traffic. (I forgot to mention this in the commit message bumping the ppm submodule, dang.)

## Includes the following PR's from ppm repo:
- https://github.com/pulsar-edit/ppm/pull/63
- https://github.com/pulsar-edit/ppm/pull/64
- https://github.com/pulsar-edit/ppm/pull/65
- https://github.com/pulsar-edit/ppm/pull/66
- https://github.com/pulsar-edit/ppm/pull/67
- https://github.com/pulsar-edit/ppm/pull/68
- https://github.com/pulsar-edit/ppm/pull/69
- https://github.com/pulsar-edit/ppm/pull/70
- https://github.com/pulsar-edit/ppm/pull/71
- https://github.com/pulsar-edit/ppm/pull/72
- https://github.com/pulsar-edit/ppm/pull/73
- https://github.com/pulsar-edit/ppm/pull/74
- https://github.com/pulsar-edit/ppm/pull/75
- https://github.com/pulsar-edit/ppm/pull/76
- https://github.com/pulsar-edit/ppm/pull/77
- https://github.com/pulsar-edit/ppm/pull/78
- https://github.com/pulsar-edit/ppm/pull/79
- [ Note: PR 80 was already included in the previous ppm bump for this core repo ]
- https://github.com/pulsar-edit/ppm/pull/81
- https://github.com/pulsar-edit/ppm/pull/83
- https://github.com/pulsar-edit/ppm/pull/84
- https://github.com/pulsar-edit/ppm/pull/85
- https://github.com/pulsar-edit/ppm/pull/86
- https://github.com/pulsar-edit/ppm/pull/90
- https://github.com/pulsar-edit/ppm/pull/91

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
Assuming all tests pass, lets get this merged!

**Comment by DeeDeeG** [comment]
My hope is to let tests run, especially I am looking for the editor tests and `settings-view` package tests still being green/passing.

**Comment by DeeDeeG** [comment]
So, we're seeing an issue I know a bit about.

> /Users/runner/work/pulsar/pulsar/dist/mac/Pulsar.app: invalid destination for symbolic link in bundle

A change (that I authored 😬) in node-gyp (https://github.com/nodejs/node-gyp/commit/b9ddcd5bbd93b05b03674836b6ebdae2c2e74c8c) leaves some symlinks that are meant to help node-gyp execute the right version of Python. Apple's signing process really doesn't like symlinks pointing to outside the signed binary's files, though.

There is a fix in node-gyp `master` already. It was merged last month, not in a tagged or published-to-npm-registry release yet. (https://github.com/nodejs/node-gyp/commit/0f1f667b737d21905e283df100a2cb639993562a)

There's a few other changes since the latest node-gyp release (v9.4.0), such as "Sync deps and engines with npm" is kinda big, but we are already out of sync with not much overlap between new node-gyp 9's deps and old npm 6's deps. `https://github.com/nodejs/node-gyp/pull/2770`.

We either need a different version of `node-gyp` in our forked npm, or back away from the `node-gyp` bump in ppm for a bit to get other ppm changes into core.

I suppose ideally I will update the references in pulsar's fork of npm 6 to point to a specific commit of node-gyp repo. But that will take some time. If I can't get to that right away, then I suggest we revert the "npm fork / bump node-gyp" stuff in ppm repo and do that over with something that won't break signing Pulsar editor on macOS.

**Comment by DeeDeeG** [comment]
PR for ppm that hopefully can address the macOS signing situation, and thereby un-block bumping ppm in Pulsar core repo: https://github.com/pulsar-edit/ppm/pull/94

**Comment by confused-Techie** [comment]
With #725 open should we go ahead and close this one?

**Comment by DeeDeeG** [comment]
@confused-Techie I have the other PR set to auto-close this one, so that should take care of it. If not, this can be manually closed. 👍

**Pull request closed without merging**
