### PR TITLE
Update ppm to commit 97f4d201be013157756a76008bf0cb55e6a1fe35

### PR DESCRIPTION
**Pull request by savetheclocktower**
PR bumping `ppm` — following the instructions from #1075.

This has only one change, but it's a major one for Apple Silicon users: native modules should now be built properly for arm64 processors on macOS.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Note: From logging the `ppm` commits, for example by clicking the comparison link from the "Files changed" tab of this PR (https://github.com/pulsar-edit/ppm/compare/d9bcff111146547e1f4dec6396d8f16f7b7ca8c8...97f4d201be013157756a76008bf0cb55e6a1fe35), I can see this bump contains the following `ppm` PRs:

- https://github.com/pulsar-edit/ppm/pull/134
- https://github.com/pulsar-edit/ppm/pull/141

I probably should have mentioned in the instructions that I usually do check the log and mention the `ppm` PRs in the core repo "bump ppm" PR, for ease of putting together the changelog later. But now, with this comment, we include the ppm PRs here (for reference when making the changelog for Pulsar 1.121.0).

**Comment by savetheclocktower** [comment]
I think [ppm#134](https://github.com/pulsar-edit/ppm/pull/134) made it into #1075, but I wouldn't bet lots of money on it.

**Review by DeeDeeG — APPROVED** [review]
Can confirm this bump was done correctly, and brings `ppm` submodule of core repo up to the current tip of ppm repo's `master` branch (https://github.com/pulsar-edit/ppm/commit/97f4d201be013157756a76008bf0cb55e6a1fe35).

Also: These changes were planned/expected to be included in core, per discussion among team members in Discord. So, this should be good for inclusion in the upcoming Regular release, IMO.

LGTM!

**Comment by DeeDeeG** [comment]
> I think [ppm#134](https://github.com/pulsar-edit/ppm/pull/134) made it into #1075, but I wouldn't bet lots of money on it.

From looking at `ppm` commit logs, looking closer at the commit ranges given in each each ppm bump PR, I think I inadvertently left https://github.com/pulsar-edit/ppm/pull/134 out of https://github.com/pulsar-edit/pulsar/pull/1075. Despite saying it was included, and intending to include it, in the now-prior bump PR (#1075).

Oh well, may as well include it now.

**Pull request merged**
