### PR TITLE
Decaffeinate.

### PR DESCRIPTION
**Pull request by fabianfiorotto**
This is the first attempt to decaffeinate pulsar. The idea is to discuss the process. I don't expect this branch is going to be merged any soon.

I used the online CoffeeScript compiler and then I edited the result:

- I replaced var with const and let in most cases
- I replaced nested ternaries operators with If statements (I didn't use optional chaining since we are targeting node 12)
- I removed some returns (I hope I didn't remove too many of those)
- I replaced for loops with for-of loops
- I  replaced some functions with arrow functions in some cases.

I wasn't able to run the test on pulsar. I just opened the editor and used it for a while. I didn't find any errors.

### CODE REVIEW

**Comment by mauricioszabo** [comment]
We're trying to make a CI build here on GitHub actions. As soon as we can, if the tests are passing, I don't see why not :)

**Comment by mauricioszabo** [comment]
@fabianfiorotto can you merge back `master` on this PR, so we can check if tests are running correctly?

**Comment by fabianfiorotto** [comment]
@mauricioszabo done.

**Comment by mauricioszabo** [comment]
@fabianfiorotto ok, the right thing is to have 21 errors on package tests and 51 on editor. Let's see if that's what happens :crossed_fingers:

**Comment by mauricioszabo** [comment]
About 100 more tests failed on the editor's specs. We may need to check what's wrong with them...

**Comment by fabianfiorotto** [comment]
@mauricioszabo I fixed some errors in the code. Now I'm getting the same amount of error messages in both branches in my local environment. You can run the test again if you want.

**Comment by mauricioszabo** [comment]
This is SO COOL, thanks a lot!

**Pull request merged**
