### PR TITLE
[autocomplete-css] Get tests passing for new CSS tree-sitter grammar

### LINKED ISSUE #587: [autocomplete-css]: Autocompletions no longer appearing in recent update
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

A new bug, seen in 1.105.2023061120 seems to have broken `autocomplete-css` autocompletions, but remains to be seen if this affects other autocompletions.

Issue details (as well as video) are over on #541

### Pulsar version

1.105.2023061120

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 11 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Create File with `.css`
2. Type in data that should warrant autocompletions, such as the following

```css
p {
  pad 
}
```

3. See that zero autocompletions are offered

### Additional Information:

_No response_

### PR DESCRIPTION
**Pull request by savetheclocktower**
This is not perfect, but it's ∞% better than the old tree-sitter CSS grammar, for which `autocomplete-css` never worked.

Fixes #587.

### Identify the Bug

#587 describes the problem: no autocompletions were working in the new CSS tree-sitter mode.

### Description of the Change

The main problem is that `autocomplete-css` uses scope information to know what tokens it should suggest, and it was expecting very specific scope names that were not present in the new grammar. In most cases, I’ve changed the grammar to use those scope names.

In one case, I changed `autocomplete-css` to look for a new scope name — the new CSS grammar uses `meta.block.inside-selector.css` for any section within a brace-delimited block, whereas the older grammars use `meta.property-list`. [CSS nesting](https://developer.chrome.com/articles/css-nesting/) is well on its way to standardization, and I didn’t want to name the scope something that would get less accurate over time. (When nesting _does_ land in a major browser, the logic of what should be suggested inside these blocks should change as well.)

I also refactored `hasScope` to cut down on redundancy and make it easier to check scopes for several different kinds of grammar (CSS, SASS, LESS, etc.) at once.

Finally, I made it so that the specs test CSS with _both_ the old TM grammar _and_ the new tree-sitter grammar. I didn’t plan to decaffeinate the spec in the process, but new tree-sitter makes it hard to avoid: since parsing can go async, one can no longer write a test that goes

1. set text in a document;
2. verify a given scope was applied to the text

without an intermediate “wait for the text to be parsed” step. That meant the specs would get _really_ complicated unless I decaffeinated and used `async`/`await`. The bad news is that this will probably broadly be true for other kinds of specs, particularly for `autocomplete-*` packages. The good news is that it gives us an opportunity to decaffeinate some stuff as we touch it.

### Alternate Designs

One alternate approach would’ve been to write a separate code path for the tree-sitter grammar and query its tree directly instead of relying on scope inspection. That would’ve added a lot more code for not much benefit, since the problems I’m about to illustrate would still be present.

### Possible Drawbacks

Here’s something about how the `tree-sitter-css` parser works that I really don’t like.

If you open an empty file and type

```css
div
```

the parser doesn’t assume that `div` is part of a selector. It won’t start assuming that until you type an opening brace or give it some other hint, like a `>` combinator. And if you were to type

```css
div:hover
```

the parser would interpret that as a property-value pair instead of a selector consisting of a tag name and a pseudoclass. This isn’t a problem in the specs because they all test scenarios in which the braces are already present, but it’s a real life problem for an autocompleter. All of this would also apply if you were at the bottom of an existing CSS file and beginning to type a selector on a new line, and I've got to think that's a pretty common scenario.

I’m not sure why `tree-sitter-css` has made this decision. This isn’t easy to work around and it makes `autocomplete-css` less useful. If I _were_ to work around it, I’d have to write some tree-sitter-specific code that would disregard scope information in certain scenarios and simply attempt to interpret the raw text on display. That’s a lot to bite off for this PR, so it’ll have to wait.

### Verification Process

Run the specs. You’ll notice there are more; there are 110 where there used to be 88. Aside from decaffeination, I don’t believe I made any changes to the specs other than the new CSS-tree-sitter testing mode and a bunch of `await`s.

### Release Notes

Fixed an issue where `autocomplete-css` was not suggesting completions when using the new modern Tree-sitter CSS grammar.

### CODE REVIEW

**Comment by savetheclocktower** [comment]
I also added a one-line change to `autocomplete-atom-api` that didn't warrant its own PR. It hadn't been working at all inside one's `init.js` because it hadn't been updated to check for a `.pulsar` directory in the file path instead of an `.atom` directory.

**Comment by confused-Techie** [comment]
Yo, what did you do here to get ARM builds passing? They haven't been working since release day

**Comment by savetheclocktower** [comment]
I swear I have no idea.

**Comment by confused-Techie** [comment]
@savetheclocktower So finally got to testing this one. Overall it looks great, and I'm now getting completions in a CSS file!

Although I am seeing some discrepancies, mainly when comparing my completions to the now Legacy Tree-Sitter. This may have been intentional, or not at all a priority. And if you feel it's not a priority, considering we are soon to remove Legacy Tree-Sitter anyway, I'm not opposed to not being worried if it doesn't work.

## Modern Tree-Sitter

image

## Text Mate

image


## Legacy Tree-Sitter

image

So like I mentioned, in the above, you can see `pad` provides zero completions for Legacy Tree-Sitter, and just wanting to check in if that's a priority for us. 

If it helps the scope in Legacy Tree-Sitter here is `source.css entity.other.attribute-name`

**Comment by savetheclocktower** [comment]
I could've been clearer about it, but I didn't try to fix legacy tree-sitter. I think some of these changes could probably be backported to legacy tree-sitter, but it didn't occur to me to try.

Consider `autocomplete-html`; someone updated that package for the legacy tree-sitter HTML grammar by creating a separate code path that queries the tree-sitter tree directly. That code path works just fine for modern tree-sitter, so we haven't had to touch that (though we only _test_ one of these code paths; I do plan to submit a PR to fix that).

By contrast, `autocomplete-css` works only by querying scopes. So the easiest way to get modern tree-sitter working was to alter `highlights.scm` so that the expected scopes are present in modern tree-sitter mode.

Give me an hour and I'll see how much of this could be backported to legacy tree-sitter. If it takes more than an hour, it's probably not worth doing.

**Comment by confused-Techie** [comment]
@savetheclocktower That sounds totally reasonable. But totally agree it isn't really a priority, since we will be removing it soon. But appreciate you checking if it is something that can be done, so this sounds rad to me, thanks!

**Comment by savetheclocktower** [comment]
OK, the old scope mapping system doesn't allow me to get quite as creative, but I've done what I can. Properties and values should get completed properly inside blocks, and _some_ selector completion will work.

**Comment by confused-Techie** [comment]
That's awesome! I'll go ahead and test this out

**Review by confused-Techie — APPROVED** [review]
Alright, this looks fantastic @savetheclocktower!
With your most recent changes, I'm getting identical completions between Tree-Sitter, Legacy Tree-Sitter, and TextMate.

Super awesome stuff

**Pull request merged**
