### PR TITLE
Remove Telemetry and Remote Crash Reports: Resolves #39

### LINKED ISSUE #39: Remove Telemetry from Core
## Summary

Currently there is Telemetry collected about the users and their usage of this application. As discussed in Discussion #2 this is behavior we should likely disable completely.

## Motivation

We don't have the eyes nor time to even review this data if we wanted, additionally as expressed in the Discussions as a community driven volunteer project there is no reason for us to collect usage data, we aren't selling a product, and I don't think it will impact the features we work on, since again as volunteers we will likely work on the aspects we care about the most. 

## Additional context

I'm hoping to make this issue to get a sense if theres any obvious points I am missing here, before starting the work myself to remove the telemetry from the repo.

### PR DESCRIPTION
**Pull request by confused-Techie**
Here I went ahead and removed all Telemetry features. Gutting the functionality by removing the config value of telemetry entirely, removing anything that starts up remote crash reporting, modifying any tests that use the telemetry or remote crash reporting, and removing dependencies to `atom/metrics` and `atom/telemetry-github`.

This doesn't have to be merged as the discussion is still ongoing, and the poll for this feature is still open.

Feel free to provide feedback.

---

EDIT:

After further testing, this works fully on `yarn install & yarn build & yarn start`

Running `yarn install` did update some of our dependencies in the yarn lock file, its possible these weren't updated on main after switching to local dependencies for some languages. But further review may be required.

### CODE REVIEW

**Comment by confused-Techie** [comment]
How do we feel about merging this new change?

Looking through it doesn't seem to cause any test failures, and looking at our current [poll](https://discord.com/channels/992103415163396136/996551773479247893/1013977155497103441)

The votes are in with 7 for this feature, and 2 against.

**Review by Spiker985 — COMMENTED** [review]
It looks like there are a few adjustments that were made which don't appear to be related to telemetry. Did we merge `master` into this branch, is that why those changes exist?

Notably some package versions and hashes

**Comment by confused-Techie** [comment]
> It looks like there are a few adjustments that were made which don't appear to be related to telemetry. Did we merge `master` into this branch, is that why those changes exist?
> 
> Notably some package versions and hashes

Any changes that are present in the `yarn.lock` file happened after running installation and building commands to test this still works. I believe the `HEAD` I grabbed at the time, hadn't had these updated after we internalized some dependencies. Since they were present on other branches I made around the same time. But if it isn't the telemetry itself, a test that relies on it, or documentation surrounding it, I'm happy to remove it from the PR if need be.

**Comment by Spiker985** [comment]
Nah, provided the non-telemetry changes are up-to-date with `master`, I see no reason to necessarily remove them, as no changes would actually occur

**Comment by confused-Techie** [comment]
Like mentioned above, with passing tests, and the community poll agreeing on this functionality, any issues brought up on the PR being resolved, I'll go ahead and merge this one.

**Comment by a-n-d-r** [comment]
Today I've installed Pulsar on a new machine, checked my `config.cson` and noticed this:
```yaml
"*":
  "exception-reporting":
    userId: "123e4567-e89b-12d3-a456-426614174000"
```

Didn't found anything related to telemetry / bug reports in the settings.
After 5 minutes of search, found the core package ["exception-reporting"](https://web.pulsar-edit.dev/packages/exception-reporting), that sends these reports.

I think we should add a checkbox in the `Settings --> Core  --> Telemetry / Bug Reporting` to remove bug reports (or at least do it without unique ID), or even make it opt-in.

**Pull request merged**
