### PR TITLE
remove metrics code from welcome package

### PR DESCRIPTION
**Pull request by Sertonix**
This removes some leftover code in the welcome packages that was used for metrics.

### CODE REVIEW

**Comment by Spiker985** [comment]
And we're absolutely sure that the code that was removed was in regards to the analytics and metrics, right? It wasn't being used by some other weird event system?

**Comment by Sertonix** [comment]
> And we're absolutely sure that the code that was removed was in regards to the analytics and metrics, right? It wasn't being used by some other weird event system?

It was only used in the metrics. You can check the `consumeReporter` function was called from the metrics system.

**Review by Spiker985 — APPROVED** [review]
Looks good to me. Places where it intersects with existing code should maintain functionality

**Review by confused-Techie — APPROVED** [review]
I'll go ahead and approve this PR then we can merge.

I do want to note that the failure rate of tests within the welcome package are higher than we would expect. But to take that with a grain of salt because these tests are highly unstable. For example the baseline taken some time ago specified an expected failure rate of 178 tests (for the welcome package group) meanwhile the PR prior to this has 480 something failing, while this has 200 something failing.

So not a blocker just pointing out. Otherwise lets merge this one

**Pull request merged**
