### PR TITLE
Bump `ppm` to `a46537c0b7f0eaaef5404ef88003951fdc988c65`

### PR DESCRIPTION
**Pull request by confused-Techie**
This PR bumps `ppm` from `4645ba2905747897b02f56d1a09ca9b3a60a6b8b` => `a46537c0b7f0eaaef5404ef88003951fdc988c65`

Which provides the following PRs:

* [`pulsar-edit/ppm#56`](https://github.com/pulsar-edit/ppm/pull/56) - "fix: Don't assume `master` when checking git packages for upgrades"
* [`pulsar-edit/ppm#54`](https://github.com/pulsar-edit/ppm/pull/54) - "meta: Normalize package.json and lockfile line endings"

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Thank you for including the ppm PRs in this PR description!! It really does help a lot with reviewing, you were very right about that! (Just seeing it now from the other side.)

I confirm the new commit SHA matches the tip of `ppm` repo... What more else is there to review? I do think I'll wait for the CI to match our expected pass/fail situation, but as soon as that happens this would be an easy approve + merge for me.

Thanks for doing this so quickly!

**Comment by DeeDeeG** [comment]
Unrelated Cirrus failure on the macOS x64 (intel) run. I think we need to `brew install python@3.10` instead of just `brew install python`, since the `python` alias points to `python3.11` as of ~yesterday. (https://github.com/Homebrew/homebrew-core/commit/d6e43416761a9b65eb7e2318444ea70da76a5e49) Python 3.11 had breaking changes that break node-gyp.

Not this PR's fault, though.

As for GitHub Actions: Package tests are in line with the usual, Editor tests are passing.

**Comment by confused-Techie** [comment]
@DeeDeeG thanks for taking a look at this! I've also noticed the Intel MacOS Build failing recently, but thanks for finding what hopefully is the cause of that, I've already made a PR to apply those changes over on #384 to hopefully get it sorted prior to our release date.

**Review by DeeDeeG — APPROVED** [review]
Approved, given that #384 appears to be working, should resolve the (unrelated) Cirrus issue identified here.

And, as mentioned above:

> I confirm the new commit SHA matches the tip of ppm repo... What more else is there to review? I do think I'll wait for the CI to match our expected pass/fail situation, but as soon as that happens this would be an easy approve + merge for me.

GitHub Actions tests are also where we expect them to be.

Thanks!!

**Pull request merged**
