### PR TITLE
Remove specific cinnamon condition

### PR DESCRIPTION
**Pull request by mauricioszabo**
Recently, I changed my desktop env from KDE to Cinnamon. Pulsar was not loading with the message:

```
╰─>$ pulsar .
/usr/bin/pulsar: line 139: ${$ACTION_PATH}: bad substitution
```

Honestly, I don't know what does lines do, and it seem flaky anyway, so this fixes the issue.

### CODE REVIEW

**Comment by Daeraxa** [comment]
Where do you see this. I've been using it with cinnamon for ages and never seen this

**Comment by mauricioszabo** [comment]
@Daeraxa when trying to load pulsar from the command line.

**Comment by Daeraxa** [comment]
The deb version? Same as I run but never seen it on mint 21

**Comment by Spiker985** [comment]
Probably only a problem on a native nemo install

I believe it is used for the Open with Pulsar action

And this would be my bad, but should be able to be fixed simply by wrapping in double quotes

**Comment by mauricioszabo** [comment]
@Spiker985 removing the second `$` does indeed fixes the issue, but I always get the error:

```
cp: cannot create regular file '/usr/share/nemo/actions/pulsar.nemo_action': Permission denied
```

So it's not perfect, and I honestly fail to see how that could even work (copying a file to a root-protected folder without sudo)

**Pull request merged**
