### PR TITLE
Fix: Image doesn't appear at first open

### LINKED ISSUE #578: [image-view] sometimes image doesn't appear at first open
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I have a problem that opened image file doesn't appear at first open. I need close it and open again, then it's OK. A console doesn't log any problem. I have debug it and the problem is CSS imo. The solution i'm used from few years is 

```less
.image-view .image-container img {
  display: block !important;
}
```

but it can be built-in into `image-view` package like at the screen below.

### Pulsar version

1.105.2023052201

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open image -> image doesn't appear
2. Close image
3. Open image -> image does appear

### Additional Information:

image

### PR DESCRIPTION
**Pull request by asiloisad**
Fix the problem of image doesn't appear at first open #578 .

### CODE REVIEW

**Comment by confused-Techie** [comment]
Hey thanks a ton for contributing on this one!
I've personally seen this issue before in the Atom days, and had totally forgotten about it.

It's awesome to see al tests passing, and I'll go ahead and test this one out. Appreciate the PR!

**Comment by asiloisad** [comment]
It my first time to make an pull request and I was make small mistake. I should create probably need to create a new branche before make a pul lrequest, because the [fix one-light sticky header](https://github.com/pulsar-edit/pulsar/pull/579/commits/84abffca559bf931edae617eb820c53304a910ef)` and `[fix one-dark sticky header](https://github.com/pulsar-edit/pulsar/pull/579/commits/09ec4c00c703a03fd96c5f57f98e02d4d52816ff) should be another one pull request. All commits are ok and work as desired, I can try to split it into two pull request if needed.

**Comment by confused-Techie** [comment]
@asiloisad I honestly wouldn't worry to much about separate PRs here, everything is one the same topic addressing the same issue, so it should really be fine

**Review by confused-Techie — APPROVED** [review]
So just tested this out, and it works perfectly! I've noticed this issue since the Atom days, so happy to see it was such a simple fix that just had to be discovered. But yeah this looks great, and I think it's good to merge!

The only thing @asiloisad is if you'd like you could add an entry to the change log, but if not we will handle it later

**Pull request merged**
