### PR TITLE
bump version to 1.102.0

### PR DESCRIPTION
**Pull request by Meadowsys**
This PR bumps the version, then reverts it, so we can build a release and continue our rolling releases from master afterwards.

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
LGTM!

**Comment by DeeDeeG** [comment]
Looking forward:

We can probably make a GitHub Action that we manually trigger to do the first commit here and push it to a branch at this repo, to get the whole ball rolling. (Particularly to trigger the Cirrus CI run that builds all the binaries.)

And then either someone manually does commit 2 to change the version string "back to `-dev`" for `master` branch/Rolling purposes, or we get automated GitHub Actions stuff going for that second part, too and maybe automatically post the draft PR, too.

(Not worried about getting "stuck on GitHub Actions" for this long-term, since it's trivial shell script level stuff, any provider's CI should be capable of this, I would think, and we have documented how to do this manually with no automation, should the need to fall back on that arise.)

**Comment by Meadowsys** [comment]
yeah would be nice to get a workflow going for everything, hit a trigger, type in a version number, it creates draft releases / triggers and uploads binaries for us, would be nice >w<

**Comment by confused-Techie** [comment]
For a task like this I'm assuming we wouldn't mind something in the `scripts` folder? I could try to take a shot at it, but would be a difficult beast to test tbh, but would love to see it.

Although I'd be more on board with trying to automate the whole thing. Updating the previous changelog entries, and leaving us to add what the most notable changes were and such, and especially get the `welcome` package automatically looking in the CHANGELOG.md or possibly it grabs it remotely if we don't include the CHANGELOG in final binaries

**Comment by DeeDeeG** [comment]
Test any workflows like this against a personal fork, I'd say. Then post here if it seems to be working.

**Pull request merged**
