### PR TITLE
remove old scripts

### PR DESCRIPTION
**Pull request by Sertonix**
This removes `script/package.json` and `spec/integration/*`. They are unused.

### CODE REVIEW

**Comment by confused-Techie** [comment]
This is the `package.json` to the original build scripts. Which we no longer use now with `yarn build` being it's replacement. 

I think this whole file may be good to actually delete, but would want to double check with @pulsar-edit/core and specifically @mauricioszabo on if there's anything of value to him in this section. Since while we aren't using it, I'm not sure if there's anything here that provides insight into how things originally worked. 

Because if not, then I'd say to just delete the whole file

**Comment by DeeDeeG** [comment]
There are a few JS scripts left under the `scripts/` dir, and some of them require modules that aren't built-in to NodeJS. So if we are using those (I'm not super familiar with them personally), then I guess we still need a `package.json` that includes those.

If we _are_ installing the packages in `script/package.json`, then removing the unneeded ones would probably speed that install up quite a bit.

There are some other modules I don't see being required elsewhere under `scripts/`, such as `electron-chromedriver`, so those could be removed too, I assume? Just going down the list of all the packages and doing `git grep [package name here]` while `cd`'d into the `script/` dir shows whether the package name is `require()`d anywhere.

**Comment by Sertonix** [comment]
The problem is that as far as I know the packages from the `scrip` directory are never installed. So the dependencies can't be loaded from there

**Review by mauricioszabo — APPROVED** [review]
Yep, these are leftovers - we aren't using them anymore with the move to electron-build!

**Review by confused-Techie — APPROVED** [review]
With @mauricioszabo's approval, lets get this merged

**Pull request merged**
