### PR TITLE
add pacman build target

### PR DESCRIPTION
**Pull request by Sertonix**
Add pacman (for arch) to build targets.

This does not work yet. I will take a look at that later.

### CODE REVIEW

**Comment by Daeraxa** [comment]
What artefact does this actually produce? Most of the time I don't see actual downloadable binaries for Arch.

**Comment by Spiker985** [comment]
Most AUR binaries are generated from deb files, or rpm files

If the current AUR bin is set to properly install from the deb, then the author could either give us ownership, or if they are comfortable with it, maintain the entry

If it's a PKGBUILD entry instead of a specific release, then they can basically just set it and forget it, provided we keep our formatting consistent

And since we have our own site redirection endpoint, it should be consistent

**Comment by Sertonix** [comment]
It creates a file that is ready to be installed with pacman via `pacman -U <file name>`.
This file could also be used if we want to publish a build to the `Arch User Repository`.

**Comment by confused-Techie** [comment]
It's worth noting, the [CI binaries](https://cirrus-ci.com/build/6045319612334080) for this PR have failed on both Linux builds.

But this new target does in fact build a `pulsar-1.100.2023010122.pacman` but looks like there would need to be special handling in the build process to accommodate it, since something is crashing when attempting to currently. Here's a more verbose output:

```
To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=linux arch=x64 electron=12.2.3 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/Pulsar-1.100.2023010122.AppImage
  • building        target=tar.gz arch=x64 file=dist/pulsar-1.100.2023010122.tar.gz
  • building        target=deb arch=x64 file=dist/pulsar_1.100.2023010122_amd64.deb
  • building        target=rpm arch=x64 file=dist/pulsar-1.100.2023010122.x86_64.rpm
  • building        target=pacman arch=x64 file=dist/pulsar-1.100.2023010122.pacman
  ⨯ cannot execute  cause=exit status 1
                    out={:timestamp=>"2023-01-01T23:26:18.698847+0000", :message=>"Process failed: /bin/sh failed (exit code 127). Full command was:[\"/bin/sh\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .INSTALL .PKGINFO usr opt\"]", :level=>:error}
                    errorOut=/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
                    command=/root/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir --force -t pacman -d c-ares -d ffmpeg -d gtk3 -d http-parser -d libevent -d libvpx -d libxslt -d libxss -d minizip -d nss -d re2 -d snappy -d libnotify -d libappindicator-gtk3 --pacman-compression xz --architecture amd64 --after-install /tmp/t-4ICfKE/1-post-install.sh --after-remove /tmp/t-4ICfKE/5-after-remove --description 'A Community-led Hyper-Hackable Text Editor
     A Community-led Hyper-Hackable Text Editor' --version 1.100.2023010122 --package /tmp/cirrus-ci-build/dist/pulsar-1.100.2023010122.pacman --name pulsar --maintainer 'Pulsar Community <noreply@pulsar-edit.com>' --url 'https://github.com/pulsar-edit/pulsar#readme' --vendor 'Pulsar Community <noreply@pulsar-edit.com>' --license MIT /tmp/cirrus-ci-build/dist/linux-unpacked/=/opt/Pulsar /tmp/cirrus-ci-build/resources/app-icons/beta.png=/usr/share/icons/hicolor/0x0/apps/pulsar.png /tmp/t-4ICfKE/9-Pulsar.desktop=/usr/share/applications/pulsar.desktop
                    workingDir=
Error building binaries
ExecError: /tmp/cirrus-ci-build/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
2
    at ChildProcess.<anonymous> (/tmp/cirrus-ci-build/node_modules/builder-util/out/util.js:235:20)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
 {
  exitCode: 2,
  alreadyLogged: true,
  code: 'ERR_ELECTRON_BUILDER_CANNOT_EXECUTE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Pull request closed without merging**
