### PR TITLE
Tree-sitter fixes (1.116 edition)

### PR DESCRIPTION
**Pull request by savetheclocktower**
This is a great one! I'm declaring victory in [our experiment](https://github.com/pulsar-edit/pulsar/issues/878#issuecomment-1920366112) from #878. We are switching Markdown parsers. The newer one is actively maintained and has fixed the one bug that was standing in the way of our original adoption.

I've also thrown in some TypeScript fixes, and I expect for there to be a few more by the time I'm done.

### CODE REVIEW

**Comment by savetheclocktower** [comment]
Taking this one out of draft a week early because of how big it is (the replacement Markdown grammar).

**Review by Spiker985 — APPROVED** [review]
_Without testing_, LGTM - when reading through there were no obvious "WTF"s 

I saw the comments in `src/wasm-tree-sitter-grammar`, do we know why that file has an activation/deactivation? It's not like that file is a grammar unto itself, so there shouldn't be any need for [de]activations, right?

**Comment by savetheclocktower** [comment]
> I saw the comments in `src/wasm-tree-sitter-grammar`, do we know why that file has an activation/deactivation? It's not like that file is a grammar unto itself, so there shouldn't be any need for [de]activations, right?

It's a grammar, but it's not a package, so you're right that it's not entirely clear why it has `activate` and `deactivate`. I had copied those over [from `tree-sitter-grammar.js`](https://github.com/pulsar-edit/pulsar/blob/master/src/tree-sitter-grammar.js#L101-L107), but I'm not sure they were ever used in that class either.

**Comment by Spiker985** [comment]
Hmm...do we know what happens if we remove them...?

**Comment by savetheclocktower** [comment]
> Hmm...do we know what happens if we remove them...?

No, but I'll leave that until next month's PR. :)

**Review by DeeDeeG — APPROVED** [review]
I am willing to sign off on that last little Python-related commit there, seems reasonable.

(Again, without manual testing or anything.)

**Pull request merged**
