### PR TITLE
Update dependency marked to v5.0.3

### PR DESCRIPTION
**Pull request by mauricioszabo**
Hopefully, no tests will fail, right?

### CODE REVIEW

**Comment by confused-Techie** [comment]
This overall looks great, but seems `notifications` tests are failing here. Weirdly enough it failed to install Pulsar at all.

I'll try running it and hope it was an issue outside your changes

**Comment by mauricioszabo** [comment]
@confused-Techie Snippets is also failing, and it seems that it's a legit failure. I'll try to tackle this :)

**Review by savetheclocktower — APPROVED** [review]
👍

**Review by confused-Techie — APPROVED** [review]
LGTM!

Glad to see we are now using the updated `marked.parse()` function, but otherwise changes look great

**Pull request merged**
