### PR TITLE
Adding highlight files for Clojure

### PR DESCRIPTION
**Pull request by mauricioszabo**
Just to illustrate the difference between time to highlight things:

TreeSitter

### CODE REVIEW

**Comment by DeeDeeG** [comment]
As I understand it, the `.wasm` file is a binary that is compiled from some other language.

Do we have the source/build stack one would need to update/re-generate this `.wasm` binary?

**Comment by mauricioszabo** [comment]
@DeeDeeG yes, I literally cloned the https://github.com/sogaiu/tree-sitter-clojure repo and called `tree-sitter build-wasm --docker .` to build the WASM file.

Maybe it's a good idea to add some metadata on grammars so we know which version we compiled... :thinking:

**Comment by DeeDeeG** [comment]
I was gonna say we should credit them, but at least legalistically there is no need as it is... _public domain_.

https://github.com/sogaiu/tree-sitter-clojure/blob/master/COPYING.txt

Maybe it'd be good to at least add a README.md, and/or some metadata fields to package.json (or some JSON or text file) so we know where this .wasm came from, some light documentation or tooling about it?

**Comment by confused-Techie** [comment]
> @DeeDeeG yes, I literally cloned the https://github.com/sogaiu/tree-sitter-clojure repo and called `tree-sitter build-wasm --docker .` to build the WASM file.
> 
> Maybe it's a good idea to add some metadata on grammars so we know which version we compiled... 🤔

We could add this to the `package.json` file maybe? So that way no change is needed at all to actual code. Could just be a field added like `tree-sitter-wasm-source` or something?

**Review by DeeDeeG — COMMENTED** [review]
Should these two empty `.scm` files be checked in?

- packages/language-clojure/grammars/ts/folds.scm
- packages/language-clojure/grammars/ts/indents.scm

If you don't mind my asking: What are they for?

**Comment by mauricioszabo** [comment]
The two scm files are checked. They are used to define how code folds (that arrow on the gutter that hides fragments of code) and how it indents (LISP-like languages have some weird indentation rules, so I decided to not check these files for now - I'm honestly thinking if we can change the indentation on Pulsar to at least do the "right" thing for these languages)

Folds, I did not implement yet for Language-Clojure, so it may be a different PR. Indent, to explain my point:

```clojure
; Suppose you have a code like this:
(defn sum-two [a b]
  (let [sum (+ a b)]
    (+ sum 2)))

; And suppose you want to add a new element just after
; the "sum (+ a b)" but before the "]". Indentation rules
; of LISP says that you need to do this:

(defn sum-two [a b]
  (let [sum (+ a b)
        <your-cursor-here>]
    (+ sum 2)))
```

This kind of "arbitrary indentation" is not yet supported on Pulsar, but I see no reason why it _shouldn't be_ supported :)

**Review by DeeDeeG — COMMENTED** [review]
This is a merge into a non-`master` branch, I don't mean to hold it up for really formal review or anything like that. I do appreciate the explanations given so far!

**Review by confused-Techie — APPROVED** [review]
While I know these PRs are not subject to a formal review, just gonna leave an approve here.
Love that you are building out what exactly is needed for anyone else to add proper language support for another language by doing this, and the answers on this thread can be super super helpful to anyone needing to do the same in the future. So thanks for all of that.

But otherwise this looks just great, and as I know Clojure is one of your favourites lets get it merged

**Comment by mauricioszabo** [comment]
Replaced by https://github.com/pulsar-edit/pulsar/pull/419

**Pull request closed without merging**
