### PR TITLE
use init.js by default

### PR DESCRIPTION
**Pull request by Sertonix**
This replaces the default `init.coffee` with an `init.js`. Both are still handled just the default is moved to match the new direction of pulsar.

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
This change looks good to me. The only thing I might recommend is making the same PR changes on `CONTRIBUTING.md` to `.github/CONTRIBUTING.md` since that is the version we will likely keep in the long run.

Otherwise looks great, and I appreciate you keeping the docs up to date during your PR's as well.

**Comment by mauricioszabo** [comment]
This is actually pretty good, I've been using the `init.js` for a while, never saw that Atom didn't change the default init script from Coffee. Merging it now :)

**Comment by Daeraxa** [comment]
We will also need to update the docs (once the CH2 PR is merged) to reflect this because it currently references the `init.coffee` in a bunch of places along with code examples.

CH3 is yet to be added (hacking-pulsar) as this has a more in-depth section on it: see the archived version here - https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#the-init-file

Also if the plan is eventually to have an "atom->pulsar" automatic onboarding, a feature to automatically migrate from the .coffee file to the .js one would be rather handy.

**Comment by mauricioszabo** [comment]
@Daeraxa can we document somewhere, maybe on some discussion, the steps we feel are needed for this `atom->pulsar` automatic onboarding to work?

**Comment by Daeraxa** [comment]
Sure, I'll make GH thread for it so we can keep track of it then maybe convert it to a project once we have an idea

**Pull request merged**
