### PR TITLE
Debounce spy

### PR DESCRIPTION
**Pull request by confused-Techie**
This debounce spyOn uses a decaffeinated `spec/spec-helper.js` to mock the implementation of `debounce` in `underscore`.

This is because on the older version of `underscore` we are using, it relies on `Date().getTime()` instead of `Date.now()` which is what we are mocking.

And thanks to @fabianfiorotto for determining this as the best solution for the problem.

With this change, it allows all tests in `spec/atom-environment-spec.js` and `spec/config-spec.js` to pass successfully. But it is important to note, that once we get `underscore` updated on `pulsar-edit/underscore-plus` this mock implementation likely will not be needed.

This PR requires PR #45 to be merged, since it contains the majority of decaffeination work done.

### CODE REVIEW

**Comment by confused-Techie** [comment]
While some of the tests are still running, the Ubuntu Tests are looking great

Editor: 24 Failed Tests
Package: 22 Failed Tests

**Comment by fabianfiorotto** [comment]
I would put the mocked debounce function in its own file. Also, we should add some comments to the code about why it was needed and how we could remove it in the future.

**Comment by confused-Techie** [comment]
@fabianfiorotto I've implemented the changes you suggested, what do you think?

**Comment by fabianfiorotto** [comment]
@confused-Techie it looks great

**Comment by fabianfiorotto** [comment]
@confused-Techie, with this change, we can rollback any other change made to `spec/config-spec.js`

**Comment by confused-Techie** [comment]
> @confused-Techie, with this change, we can rollback any other change made to `spec/config-spec.js`

Great catch. I've reverted those changes on this branch.

**Comment by mauricioszabo** [comment]
LGTM :+1:

**Review by mauricioszabo — APPROVED** [review]

**Comment by confused-Techie** [comment]
Rad, so with approval, and having had a few eyes looking at this, and the tests looking great I'll go ahead and merge. Thanks to everyone here that's contributed!

**Pull request merged**
