### PR TITLE
Standardize theme package names/descriptions

### PR DESCRIPTION
**Pull request by Spiker985**
- Rename themes to `theme-<ui|syntax>-<theme name>` syntax
- Renamed `atom-dark-syntax` to `theme-syntax-atom-dark`
	- Since this is a theme, it can keep the Atom branding as it **is** an Atom theme
- Renamed `atom-light-syntax` to `theme-syntax-atom-light`
	- Since this is a theme, it can keep the Atom branding as it **is** an Atom theme
- Renamed `atom-dark-ui` to `theme-ui-atom-dark`
	- Since this is a theme, it can keep the Atom branding as it **is** an Atom theme
- Renamed `atom-light-ui` to `theme-ui-atom-light`
	- Since this is a theme, it can keep the Atom branding as it **is** an Atom theme
- Renamed `base16-tomorrow-dark-theme` to `theme-syntax-base16-tomorrow-dark`
- Renamed `base16-tomorrow-light-theme` to `theme-syntax-base16-tomorrow-light`
- Renamed `one-light-syntax` to `theme-syntax-one-light`
- Renamed `one-dark-syntax` to `theme-syntax-one-dark`
- Renamed `one-light-ui` to `theme-ui-one-light`
- Renamed `one-dark-ui` to `theme-ui-one-dark`
- Renamed `solarized-dark-syntax` to `theme-syntax-solarized-dark`
- Renamed `solarized-light-syntax` to `theme-syntax-solarized-light`

### CODE REVIEW

**Comment by confused-Techie** [comment]
I cannot believe how many specs rely on the names of specific themes and UIs, but the `Editor tests / test (ubuntu-20.04)` we are getting 33 failures, when we expect 1 or 0. So these will have to be sorted before it can be merged

**Comment by Spiker985** [comment]
:facepalm: I really gotta start using Ctrl + Shift + F when doing these. Let me get those specs updated

**Comment by Spiker985** [comment]
image
...why..._why_ does it prefix the name with theme?!

Does that mean that I need to update these specs to be `theme-theme-syntax-atom-dark`?!

**Comment by confused-Techie** [comment]
> image ...why..._why_ does it prefix the name with theme?!
> 
> Does that mean that I need to update these specs to be `theme-theme-syntax-atom-dark`?!

Yeah wild, based on that I would assume you would have to for the specs. But awesome work, nearly all of the failing tests are fixed

**Comment by Spiker985** [comment]
@confused-Techie Might I request a review (once the CI finishes)

**Review by confused-Techie — APPROVED** [review]
This overall looks great to me.

There was one set of tests that were not reporting the amount of failures they had, so I've rerun them (git-diff, go-to-line, grammar-selector...) and we will see how those resolve.

Otherwise like these changes and everything looks valid.

**Comment by Spiker985** [comment]
Deviation is too much now. Perhaps one day we'll get to do this again.

**Pull request closed without merging**
