### PR TITLE
Update Pulsar's Linux desktop & metainfo mostly from Flatpak

### PR DESCRIPTION
**Pull request by cat-master21**
## Changes
This PR updates/adds to the Linux metadata upstream, `dev.pulsar_edit.Pulsar.metainfo.xml` from the Pulsar Flatpak metadata at https://github.com/flathub/dev.pulsar_edit.Pulsar/blob/master/dev.pulsar_edit.Pulsar.metainfo.xml.

## Release Notes
* Update (Linux) metainfo from downstream Pulsar Flatpak

### CODE REVIEW

**Comment by confused-Techie** [comment]
Thanks a ton for contributing! These changes look to make sense to me, and I'm happy to get this one merged unless any of our other more Linux focused devs have anything to add?

**Comment by cat-master21** [comment]
As it is however, I have decided to make this a draft, as Pulsars' metadata could be improved upon more such as having branding colors.
Screenshot from 2024-02-25 18-57-50

**Comment by DeeDeeG** [comment]
I read Flathub's guidelines for this stuff a bit:

- https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines
- https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines

In following with what they suggest, maybe we can do the following:

Summary:

> Hyper-hackable text editor

(My thinking: This fits within the 35 character limit per the guidelines. Guidelines say things like "open source" or "using this framework" or "has this ethos" should not be in the summary, it should be "what can people do with the app, what does it do?" I reckon "text editor" covers that base, although I considered "Edit code just how you like." (???). But also, the guidelines say the summary is kind of a slogan or advertisement, and "Community-led hyper-hackable text editor" has been the tagline since really early days, it should resemble that, IMO. We can move "community-led" to the overhauled description, see below. Again, for the sake of staying under the character limit. Also adjust capitalization per the Flathub guidelines. Though I kind of like having our own style flair with the capitalization, and the guidelines for the description aren't _mandatory_, just guidelines, so hmmmmmmmm...)

Description:

> Pulsar is a community-led project built from the ashes of the much-loved (now sunset) Atom editor.
> It is intuitive to start using, while remaining deeply customizable for those who want or need to.
> Add-on packages are available to customize the editor and add functionality.
> You are welcome to make and publish your own packages as well!

(My thinking: This seems to be in the vibes of what the guidelines wants from us here? And the current description is still "Pulsar is still brand new, we aspire to a lot, watch this space" whereas we aren't brand new and we're pretty established at this point. And we don't need to define our _goals_ in terms of Atom, we _started_ from Atom and carry some of that ethos forward, but "reaching feature parity with Atom" was achieved more or less day 1 when we forked and as soon as the package registry was live, basically. So, not an ongoing goal as much as checklist item completed, IMO.

This should be readable to a _total newcomer_ who has never heard of _us or Atom_ before. While giving context about our roots and such.)

Screenshot:

They really want that app window chrome and drop shadow, don't they? Dang. I guess we might be able to re-stage the Readme screenshot to be more window chrome-y and drop-shadow-y? Maybe?

App Icon:

Maybe I can download their icon gridlines thing and re-size our circle logo SVG so it's _just right_ per their guidelines? I don't think it can possibly be very far off, but eh, they seem to care a bunch about it.

Brand colors:

Blarg, gotta come up with something the app icon would be legible on. Maybe a tint of the logo purple, or I can try and dig through the design mockups we got from the professional graphic designer that one time and see if we got some good backdrop colors/tints the logo can sit well on, for light + dark theming. (Side note: Seems to be used moreso for their app store/site than as necessarily _our actual brand colors_, so I dunno if I agree with their naming of what these colors are about, but eh...)

Developer name:

We can reformat this to use

```xml
<developer>
  <name></name>
</developer>
```

Per: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#name-summary-and-developer-name

---

So, a few little to-dos, maybe. I think the brand colors one might be the most pressing, if they're really going to start enforcing that like the screenshot above kind of implies??

**Comment by cat-master21** [comment]
So @DeeDeeG I have been looking into this and have made a PR at https://github.com/flathub/dev.pulsar_edit.Pulsar/pull/36 in addition to the metadata already committed in the Pulsar Flatpak. Flathub aside, if this requires other assets, I am not sure as to how this will be packaged by Pulsar.

**Comment by DeeDeeG** [comment]
Okay, thanks for linking that PR over at the flathub repo, @cat-master21.

Speaking for myself personally, I approve of those efforts generally to comply with their linter and the spirit of their guidelines, and we can all try to have some sort of consensus-oriented discussion here to update the various strings/colors/etc. if there is enough interest/participation here. Otherwise, just something that passes their linters and is basically in keeping with what it was before-ish is a safe way to proceed if there is no obvious consensus, IMO.

In other words, I would like to see some some suggestions discussed with people here and trying to get multiple people okay with the same values for the metadata before considering them blessed by the group as a whole, whereas I am okay with the light maintenance stuff in https://github.com/flathub/dev.pulsar_edit.Pulsar/pull/36 happening until then, personally.

I am working on other stuff at the moment, I had simply chimed in above (https://github.com/pulsar-edit/pulsar/pull/935#issuecomment-1971460285) with my thoughts as I had a free moment to do so at the time.

But yeah, all is well IMO. Sorry if the async and/or very light amount of communication has been unclear at any point, but nevertheless I think it's all good, IMO personally.

And thanks for keeping us posted on the updates/changes that the metadata guidelines are asking for or their linter is asking for, etc.

**Comment by cat-master21** [comment]
So I have been looking at improvements, and it looks like the icon should be 120px instead of 128px:
Screenshot from 2024-03-09 11-59-02
Fixed (120px):
pulsar-mockup
I have no idea where the Linux icon is packaged, and also a screenshot would be added showing the app window and shadows:
Screenshot from 2024-03-09 12-40-02
@confused-Techie & @DeeDeeG what do you think of this? This is not required to update the Pulsar Flatpak in Flathub so no rush.

**Comment by DeeDeeG** [comment]
I like the screenshot, looks pretty native to a GNOME desktop where FlatHub apps are probably most used at this point (besides KDE, etc?). If this satisfies their oddly specific need for window chrome and drop shadow, then that's great!

Icon appears to have been scaled proper with the vector art, and lines up with their template thingy, which should be great, again per their oddly specific requests. (I guess it's good for them to be opinionated about design, and for them strive for a consistent app [browsing/usage] experience within their ecosystem...)

---

> I have no idea where the Linux icon is packaged

It's defined here in the `electron-builder` config script: https://github.com/pulsar-edit/pulsar/blob/7740b2f16812f811f0f2c95ae0edd5f771f93f26/script/electron-builder.js#L43

Config is pointing to the actual icon files stored here in the repo --> https://github.com/pulsar-edit/pulsar/tree/7740b2f16812f811f0f2c95ae0edd5f771f93f26/resources/app-icons

**How to get the flatpak to use a different icon than the .deb?**

Maybe the little build script here (https://github.com/flathub/dev.pulsar_edit.Pulsar/blob/cecb17c99bcd9f9ed74c0a2f4640f90aace443bf/dev.pulsar_edit.Pulsar.json#L98-L110) can fetch a re-scaled icon from somewhere and replace the one from the `.deb` with it before finally re-packaging as a flatpak?

**Where to host the scaled SVG?**

- Ideally we would see if the re-scaled icon seems nicer for the .deb itself, in which case replace the SVG the .deb uses with this scaled-down version.
- If the full-scale SVG is preferred for the .deb, or for whatever reason replacing the original SVG is not desirable, we can host it with a new filename as `bate-flatpak.svg` or some such, and the little downloader script linked just above can fetch it from there?
- The flatpak repo itself could host the re-scaled icon, but if we ever update the main repo's icon we should probably update the flatpak icon at the same time, and hosting it in the official main repo would be a good reminder to change the flatpak one as well. **As in, probably we should host the scaled icon at the official main repo, if possible, I reckon?**

**Comment by cat-master21** [comment]
Also I have updated Pulsar's Linux desktop file with support for opening `application/x-zerosize;` ([zero sized file](https://gitlab.gnome.org/GNOME/glib/-/issues/2777)) and also adding desktop support with opening a new tab instead of entire window like what [Gnome Text Editor does](https://gitlab.gnome.org/GNOME/gnome-text-editor/-/blob/main/data/org.gnome.TextEditor.desktop.in.in#L20) in my newest commit[`cc2188f`](https://github.com/pulsar-edit/pulsar/pull/935/commits/cc2188fe744ee912a299435010b829a21db0a174).

**Comment by cat-master21** [comment]
Thanks for the info @DeeDeeG. I found what you said to be true except that **Pulsar does not use the SVG or a single PNG!** This is packaged in Pulsar's deb at `/opt/Pulsar/resources/pulsar.svg` & `/opt/Pulsar/resources/pulsar.png`. However I have found that these are not the icons being used, instead the deb, rpm, and flatpak uses the ones packaged at `/usr/share/icons/hicolor/.../apps/pulsar.png` (`...` being size). These icons can be found https://github.com/pulsar-edit/pulsar/tree/master/resources/icons.
https://github.com/pulsar-edit/pulsar/blob/7740b2f16812f811f0f2c95ae0edd5f771f93f26/script/electron-builder.js#L169-L178

My solution to this is to instead delete the scaled icons and use a single SVG that is scalable as the main desktop icon and place it at `/usr/share/icons/hicolor/scalable/apps/pulsar.svg` which is what many applications do nowadays.

In addition to the desktop & metainfo file changes done, another change I plan to implement is to actually package the appdata/metainfo at `/usr/share/metainfo` so that when locally installing from KDE Discover or Gnome Software, it will look *almost* the same as the Flatpak (not looking blank).
What installing the **local rpm or deb** currently looks like under Gnome Software:
image

**Comment by DeeDeeG** [comment]
Here's how the updated icons look in Linux Mint MATE 21, at least on my machine.

### Taskbar

Before:
before -- taskbar
After:
after -- taskbar

(Looks pretty much identical to me.)

### MintMenu

<details><summary> Before/after images of the Pulsar icon in MintMenu (click to expand):</summary>
 
 Before:
before -- MintMenu
After:
after -- MintMenu

</details>

(If you look closely, the icon is smaller with this change, and the fine details are less-well resolved, in my opinion.)

**Comment by DeeDeeG** [comment]
I think it'd be good to keep the icons as-is for non-Flatpak packaging. The larger icon scaling, visually taking up the full size of its dimensions, resolves better for small icon sizes where fine details don't resolve as well otherwise. (And perhaps some SVG scaling is being done by the OS with a fast but not as good-looking algorithm compared to the manually exported PNGs?)

Can we revert the icon changes for the .deb and .rpm use-case, and apply the new scaled SVG only for purposes of the Flatpak?

**Comment by cat-master21** [comment]
Okay then @DeeDeeG I have reverted the icon changes, but the SVG is still under `resources/linux/pulsar.svg` for the Flatpak.

**Review by DeeDeeG — APPROVED** [review]
Looks good to me! Thanks for bearing with all the discussion and async communication, some delays, etc.

**Pull request merged**
