### PR TITLE
Fixing documentation/noting potentially at-risk links

### PR DESCRIPTION
**Pull request by preland**
### Description of the Change

Fixing documentationnoting potentially at-risk links

### Release Notes

-Added notation for documentation files that appeared to be little more than leftovers from Atom. Some files might be false flagged, and those are marked as such.

-Added comments throughout the codebase whenever a link to the official Atom repo was mentioned, as these links may become obsolete after sunset, and may need to be altered/preserved to maintain an understanding of the original source code, as well as future-proofing the codebase.

-Also did a few minor tweaks to client-side text; most notably changing the crash reporting website listed from github.com/atom/atom to github.com/pulsar-edit/pulsar/issues/new/choose. While I don't personally think these minor changes warrant an extra pull request, these changes could be removed and added to another pull request.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Going through this looks fantastic currently. Although heres a few requests/recommendations.

For things like the PR Template, or Issue Templates, those can be removed entirely since we have those propagating through our `.github` repo, and once removed the repo will just use whats there, as that is what we are doing on every other repo.

Additionally for the `CONTRIBUTING.md` file I would recommend changing that to our current recommend format, as detailed in our [contributing docs](https://github.com/pulsar-edit/.github/blob/main/project-birth/CONTRIBUTING-DURING-START.md#simplifying-and-bringing-up-to-our-standards). And lastly for what I've found so far, it may be best to change the `CODE_OF_CONDUCT.md` file here to be an exact copy of the current code of conduct that contributors have drafted available [here](https://github.com/pulsar-edit/.github/blob/main/CODE_OF_CONDUCT.md).

But thanks for the contribution, this looks great so far!

**Comment by preland** [comment]
Thank you for the feedback. I have added your recommendations to the PR with the latest commit, as well as fixed some other minor issues with the PR.

**Comment by confused-Techie** [comment]
> Thank you for the feedback. I have added your recommendations to the PR with the latest commit, as well as fixed some other minor issues with the PR.

Thanks for taking another look at this. I'll go ahead and review this as soon as I can

**Comment by Spiker985** [comment]
@preland Would you mind reviewing the conflicts on this PR?

**Comment by preland** [comment]
I will take another look at this PR, as it seems like a lot has changed in the codebase since its initial commit.

**Comment by Spiker985** [comment]
Is this still needed?

**Comment by confused-Techie** [comment]
> Is this still needed?

I'm sorry to say to @preland but this may not be needed at this point.
Since we never did go the way of including more of the community health files into individual repos, and we actually started moving them mostly out.

Additionally, since then we have had the whole discussion of what not to change, siding with not modifying historical data using terms like "Atom" or "GitHub" as that would make them inaccurate, which is happening a lot in this PR.

Plus, considering the huge amount of conflicts, through no fault of the author, it may be best to recreate this PR again if we deemed necessary. But @preland feel free to reopen this or create a new PR updated from `master` if you want to get these changes in. Sorry we couldn't get to it originally, but at this point it might just be to out of date.

As always appreciate any contributions @preland

**Comment by preland** [comment]
No, I completely agree, this PR isn't exactly necessary or relevant (or even mergable) currently. Plus, I'm pretty sure the brunt of the concerns that I had have already been addressed by others since the last commit to this PR. 

In the case that I feel there is still more to be done, I may make a new PR with some of these changes.

Either way, thank you for your consideration!

**Pull request closed without merging**
