### PR TITLE
Update package.json endpoints to point to github

### PR DESCRIPTION
**Pull request by Spiker985**
Rather than use atom's dying services - should resolve http 5XX responses when trying to build.

Confirmed downloads from origin url and github url are the same via SHA512 hash.

Courtesy of schwarzkatz in the Discord

### CODE REVIEW

**Comment by Spiker985** [comment]
Assumed this would be best to merge to master, then cherry picked to other existing branches where possible

**Comment by Spiker985** [comment]
For context: 

`codeload.github.com` is the service which provides archives for download.
GET Requests to `api.github.com` for archives redirect to `codeload.github.com`

Attempting to navigate to `https://www.atom.io/api/packages/archive-view/versions/0.66.0/tarball` actually 302s to `https://codeload.github.com/atom/archive-view/legacy.tar.gz/refs/tags/v0.66.0`

**Review by confused-Techie — APPROVED** [review]
Just want to point out that we can safely revert these changes once the backend is up. But otherwise this can save us some issues that are currently being experienced.

**Comment by Spiker985** [comment]
I'm going to close this, sync my fork, make a new branch for this edit explicitly, and resubmit - because that's proper form and I want to try some things anyway

**Pull request closed without merging**
