### PR TITLE
Bump `snippets` to bb00f9

### PR DESCRIPTION
**Pull request by savetheclocktower**
Bumps `snippets` from `fe00fd6933fa33f819d14cdd6938d538d25ba1dd` to `bb00f909c6c645b173f27346875d8fa0c7af09f7`.

Provides the following PRs:

* [`pulsar-edit/snippets#10`](https://github.com/pulsar-edit/snippets/pull/10): “Add `command` property that registers a command name for a snippet” 
* [`pulsar-edit/snippets#7`](https://github.com/pulsar-edit/snippets/pull/7): “Remove implicit `g` flag from snippet transformations”
* [`pulsar-edit/snippets#6`](https://github.com/pulsar-edit/snippets/pull/6): “Fix failing specs”
* [`pulsar-edit/snippets#5`](https://github.com/pulsar-edit/snippets/pull/5): “cleanup and rename”

Let me know if this should be done a different way. I ran

```sh
npm install "https://github.com/pulsar-edit/snippets.git#bb00f909c6c645b173f27346875d8fa0c7af09f7"
```

and `npm` converted it to the syntax you see in the `package.json`. I’m also not wild about how much `yarn.lock` got changed for such a small update.

### CODE REVIEW

**Comment by Spiker985** [comment]
Something I've noticed, is that doing any `npm` operations, updates the urls of the `yarn.lock` to no longer point to yarnpkg

So I've deleted the `yarn.lock`, and recreated it with a simple `yarn install` so it's maintained

We do use yarn for this repo, but both so long as either npm or yarn update the dependencies appropriately - they should both be fine. I do recommend having `yarn` recreate that lock file though, please

**Comment by savetheclocktower** [comment]
Ah, muscle memory always leads me to `npm`. I should setup a `dotenv` in the directory to yell at me if I try to upgrade via `yarn`.

**Comment by savetheclocktower** [comment]
Oof. `yarn install` works until:

```
error An unexpected error occurred: "ENOENT: no such file or directory, scandir '/Users/andrew/Code/JavaScript/pulsar/node_modules/styleguide/node_modules/atom-select-list/node_modules'".
```

`/Users/andrew/Code/JavaScript/pulsar/node_modules/styleguide` exists but is empty.

**Comment by Spiker985** [comment]
I'd drop your entire `node_modules` folder, drop the `yarn.lock` file, and then redo the `yarn install`

Since that's going to replicate how our CI environments will start _anyway_

**Comment by savetheclocktower** [comment]
OK, `yarn.lock`'s diff is nowhere near as big now (though still somewhat big).

**Comment by DeeDeeG** [comment]
Just a comment on the `yarn.lock` situation, I have found that this is a thing going back at least as far as npm 8.x.

To a certain extent, this rises to the level of being a bug (https://github.com/npm/cli/issues/5126).

(I think they change it intentionally, but it'd be nice if they didn't change it at all, IMO, which was the status quo in npm 6.x that they have since changed in newer npm.)

**Review by confused-Techie — APPROVED** [review]
Thanks a ton for doing this, and thanks a ton for properly including the PR's that have been merged!

**Comment by DeeDeeG** [comment]
So, unfortunately, newer npm doesn't really play nice with `yarn.lock`, and I'd say it's preferable to update `yarn.lock` only with Yarn.

(And to clarify, that is yarn v1 anywhere in the Plsar org, also known as `yarn` on the npm package registry (not yarn 2.x or 3.x known as "Yarn Berry"), so you can get it with **`npm install -g yarn`**, or in recent NodeJS with corepack, you can do `corepack enable`).

If you want to do just the `package.json` change, that's be okay, but syncing the lockfile when dependencies in `package.json` change is definitely better.

**Review by DeeDeeG — CHANGES_REQUESTED** [review]
I'm not confortable with this much `yarn.lock` changes for a simple dependency bump. It's changing things like babel versions.

I volunteer to re-do this with Yarn and save the `yarn.lock` that way if it will be helpful, can push to this branch if you are comfortable with that @savetheclocktower, or I can let you do it if you prefer.

(EDIT: It would be, use the lockfile as of before this PR (so, like `git restore --source=origin/master yarn.lock`, assuming your remote is called `origin` and commits you have fetched locally are up-to-date such as by running `git remote update`) and then simply `yarn install` again. I _think_ with or without `node_modules` present shouldn't matter with Yarn, could be wrong, but it should matter _much_ if it does at all.)

**Comment by savetheclocktower** [comment]
So I specifically did re-do this with yarn; that was the “Fix yarn.lock” commit. But please do give it a shot and let me know if you were able to get the diff smaller.

**Comment by DeeDeeG** [comment]
The diff can apparently just be the following:

```diff
diff --git a/yarn.lock b/yarn.lock
index ed8088d21..6dc0b865b 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -8694,9 +8694,9 @@ smart-buffer@^4.0.2, smart-buffer@^4.2.0:
   resolved "https://registry.yarnpkg.com/smart-buffer/-/smart-buffer-4.2.0.tgz#6e1d71fa4f18c05f7d0ff216dd16a481d0e8d9ae"
   integrity sha512-94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==
 
-"snippets@https://github.com/pulsar-edit/snippets.git#fe00fd6":
-  version "1.6.1"
-  resolved "https://github.com/pulsar-edit/snippets.git#fe00fd6933fa33f819d14cdd6938d538d25ba1dd"
+"snippets@github:pulsar-edit/snippets#bb00f909c6c645b173f27346875d8fa0c7af09f7":
+  version "1.7.0"
+  resolved "https://codeload.github.com/pulsar-edit/snippets/tar.gz/bb00f909c6c645b173f27346875d8fa0c7af09f7"
   dependencies:
     async "~0.2.6"
     atom-select-list "^0.7.0"
```

Let me know if you want me to push this to this PR's branch (assuming we are granted write access to the PR branch.)

**Comment by savetheclocktower** [comment]
> Let me know if you want me to push this to this PR's branch (assuming we are granted write access to the PR branch.)

By all means! You've got write access to this branch. Appreciate it.

**Review by DeeDeeG — APPROVED** [review]
Approving that this is a validly performed dependency bump.

I can also confirm this PR is bumping to the commit at the tip of the "snippets" repo's `master` branch at the moment I'm writing this (`bb00f909c6`), which I confirm _does_ include at least the four PRs mentioned in this PR's description.

(Note: Some PRs were merged at "snippets" repo with merge commit messages that don't mention the PR # in the first line, but they do mention the PR number in the body text/subsequent lines of the merge commit message.)

<details><summary><kbd>git log --graph --oneline</kbd> output (click to expand):</summary>

It's easier to see in graph view, but this output is much more readable if you run this locally, due to color-coded graph lines.

```
% git log --oneline --graph 388d9b6~3...origin/master
*   bb00f90 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #5 from Sertonix/cleanup-and-master
|\  
| *   0bbbeac Merge branch 'master' into cleanup-and-master
| |\  
| |/  
|/|   
* |   12eec6d Merge pull request #6 from pulsar-edit/fix-tests
|\ \  
| * \   3cd111d (origin/fix-tests) Merge branch 'master' into fix-tests
| |\ \  
| * | | fe00fd6 Fix failing specs
* | | |   76a32e5 Fix global flag on snippet transformations
|\ \ \ \  
| |_|/ /  
|/| | |   
| * | | c5c73c0 Update version to 1.7.0
| * | | cebceda Remove implicit `g` flag from snippet transformations
|/ / /  
* | |   d0c574a [feat] Add command property to Snippet entries
|\ \ \  
| |/ /  
|/| |   
| * | 91076f5 Update .github/workflows/pulsar_test.yml
| * | 8f87140 Apply suggestions from code review
| * | 6410899 Fix spec failure on Windows
| * | 159459f Workflow attempt 2
| * | d4835d8 Testing a branch of action-pulsar-dependency
| * | 5bf4a85 Debounce the user-snippets-file-changed handler
| * | 34bd7ff Fix failing test
| * | e8c3495 Update README.md.
| * | 8133849 Add tests.
| * | d944225 Add ability to assign a snippet to a command name
| * | 29deddc Add eslint
|/ /  
* | 009b767 (deedeeg/master) Fix typo
| * 4b9d45c remove coffeelint
| * 26695d8 cleanup and rename
|/  
*   388d9b6 Merge pull request #2 from Sertonix/remove-fs-plus
[ . . . snipped more commits . . . ]
```

</details>

**Comment by confused-Techie** [comment]
Alright, with two approvals on this PR I'll go ahead and merge it.

Thanks @savetheclocktower for this one, we appreciate you!

**Pull request merged**
