### PR TITLE
Update LICENSE.md

### PR DESCRIPTION
**Pull request by Daeraxa**
Update the MIT Licence with Pulsar

Added "MIT License" to the top as provided by the template at https://choosealicense.com/licenses/mit/ and also the standard template from GH.

Adds a Copyright line for "2022 Pulsar-Edit" - feel free to suggest if this should be different, e.g. "Pulsar", "pulsar-edit" (repo name) or "Pulsar Team/Community" or something.

Moves the GH line down but adds "original work" wording to the start.

The actual licence wording is identical but just reformatted in regards to newlines by what is provided by https://choosealicense.com/licenses/mit/ and the GH MIT licence template. This was checked by removing *all* whitespace and comparing the two strings which came out to no differences.

### CODE REVIEW

**Review by Sertonix — APPROVED** [review]
I approve this pull request because it does what it should.
But this pull request could also update the `LICENSE.md` of the packages in this repository.

**Comment by Daeraxa** [comment]
Good point, I hadn't even thought of those, I can go and do those as well.

**Review by confused-Techie — APPROVED** [review]
This looks great to me!

The `Pulsar-Edit` really makes sense as that is our Org name, and kinda encompasses all of us.
As for adding in the other packages, I'd honestly rather see those removed. As we are using the same license everywhere, and that code is now in this repo. Unless we need to do any fancy duel licensing on any bundled packages, I'd vote to just remove them. 

But regardless, that feels a bit out of scope here, so I'll approve, and leave for a bit before merging to ensure others are able to review as well.

**Comment by Daeraxa** [comment]
I've been through the others, there are more than a few which are more than just the MIT licence, for example the typescript one has a MS copyright and all the converted textmate grammars have their original repo licences appended too which we should be keeping.

I'll do these in a separate PR

**Comment by confused-Techie** [comment]
> I've been through the others, there are more than a few which are more than just the MIT licence, for example the typescript one has a MS copyright and all the converted textmate grammars have their original repo licences appended too which we should be keeping.
> 
> I'll do these in a separate PR

That sounds awesome to me. Remove that which is a normal MIT license. But for the others that sounds like a great plan. I'll merge this one and let you start on that then

**Pull request merged**
