### PR TITLE
Making autocomplete-plus work to replace ranges

### PR DESCRIPTION
**Pull request by mauricioszabo**

### CODE REVIEW

**Comment by savetheclocktower** [comment]
This is for choosing an autocomplete option when text is selected?

How would one make the autocomplete menu appear in that scenario?

**Comment by mauricioszabo** [comment]
Actually (and I should have opened this as Draft) it's to decide what to replace.

Currently, Autocomplete works by: for example, if I type `console.lo`, and the suggestion says `text: "log", prefix: "console."`, it'll replace what's _after_ the prefix with `log`.

But some LSP providers allow for fuzzy-finder matches - like, I can type `console.lg`, and it'll match `log`, and say "hey, replace `<range>` with `"log"`". This API is to start to support this kind of API

**Comment by savetheclocktower** [comment]
OK, so sounds like this wouldn't change any behavior for existing providers until they were updated to support it. Understood.

**Comment by mauricioszabo** [comment]
Yes, the new version will only be used if some provider declares that it supports the new version.

**Comment by confused-Techie** [comment]
@mauricioszabo Hate to do this to you, but would you mind getting the newest changes from master so we can see green CI before a merge

**Comment by mauricioszabo** [comment]
@confused-Techie after a couple months, done :laughing:

**Review by confused-Techie — APPROVED** [review]
@mauricioszabo Thanks a ton for taking the time to get this updated!

And the changes here look great, and love to see tests passing (Beside macOS failing to build, but that issue lies somewhere else, not here).

Especially having a solid spec to lean on for implementation details later, and being able to write up documentation for, this looks incredibly solid, and I say lets get this merged!

**Comment by mauricioszabo** [comment]
Ok, @confused-Techie, let me just update the changelog :)

**Review by confused-Techie — APPROVED** [review]
LGTM! Lets get this merged

**Pull request merged**
