### PR TITLE
script: symlink ppm in post-install.sh (for .deb and .rpm packages)

### PR DESCRIPTION
**Pull request by DeeDeeG**
This is run at the end of installation of the .deb and .rpm binaries

<details><summary><b>Requirements for Adding, Changing, or Removing a Feature</b> (from template, click to expand):</summary>

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must contribute a change that has been endorsed by the maintainer team. See details in the template below.
* The pull request must update the test suite to exercise the updated functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

</details>
 
### Issue or RFC Endorsed by ~~Atom's~~ Pulsar's Maintainers

See: https://github.com/pulsar-edit/pulsar/issues/187 / https://github.com/pulsar-edit/pulsar/issues/187#issuecomment-1366385727

### Description of the Change

In the post-install.sh script that's run at the end of the .deb and .rpm package installs, create a symlink to `/opt/Pulsar/resources/app/ppm/bin/apm` at `/usr/bin/ppm`.

(This is right after we copy `pulsar.sh` to `/usr/bin/pulsar.sh`.)

See the diff.

### Alternate Designs

- Maybe we should be installing these things to `/usr/local/bin` instead of `/usr/bin`, in order to conflict less with the one or two distro packages that use the same binary names/paths? (See  pkgs.org links in "Possible Drawbacks" below.)
- This could be a little more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), maybe. It's just that in the first half of the script we're using `cp` to copy, and then in the bottom half we need to use `ln` to symlink. So it would make any DRY-er solution probably more complicted than it needs to be.
  - If someone is a shell script wizard that wants to make this cooler, without it becoming harder to follow whats going on, then I'm fine with that, but right now it's basic and it works.

### Possible Drawbacks

- Maybe some users prefer `ppm` to not be on their PATH???
- The path `/usr/bin/ppm` would conflict with a "Perl PPM scripts" package on ALT Linux, whatever that is: https://pkgs.org/search/?q=%2Fusr%2Fbin%2Fppm
  - Note: `/usr/bin/pulsar` already conflicts with the `odin` package, which is apparently something to do with MRIs (the medical diagnostic imagery technology). https://pkgs.org/search/?q=%2Fusr%2Fbin%2Fpulsar  

### Verification Process

I simply ran this in the git repo as `sudo sh script/post-install.sh`, and it worked as intended. (The script only uses absolute paths, no relative paths, so it should work the same regardless of where it's run from.)

**TODO:** Test an actual built .deb just to be sure? (Someone on Fedora or an .rpm based distro can test the .rpm?)

### Release Notes

Symlink ppm to PATH after install (for the .deb and .rpm packages only)

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
I was hoping to let someone more familiar with these systems review first.

But otherwise the change sounds fantastic, I'm currently unable to test it, but when possible will try to reach out to any of our Linux users to test the binary that should now be built.

Thanks for getting this one done, a much needed fix

**Comment by joshcangit** [comment]
Tried to make a symlink like this.
It does indeed work.

However, I settled on using a wrapper instead.

**Comment by Daeraxa** [comment]
So I just installed one of the very latest .debs on an MX Linux (Debian) VM. Testing this wasn't my intention so I don't have the "before" results.

Basically `pulsar` is working fine but if `ppm` was meant to be linked too, this doesn't seem to work.

```
dae@mx:~
$ pulsar --version
Pulsar  : 1.100.2022122803
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
dae@mx:~
$ ppm
bash: ppm: command not found
dae@mx:~
$ which pulsar
/usr/bin/pulsar
dae@mx:~
$ which ppm
dae@mx:~
```

**Comment by DeeDeeG** [comment]
@Daeraxa

> Pulsar  : 1.100.2022122803

That version number doesn't match what I'm seeing in this PR on Cirrus.

> Uploaded /tmp/cirrus-ci-build/binaries/pulsar_1.100.2022122807_amd64.deb

In fact it looks like this run from `master` branch: https://cirrus-ci.com/task/4920915293634560?logs=binary#L8

> Uploaded /tmp/cirrus-ci-build/binaries/pulsar_1.100.2022122803_amd64.deb

So, in that case you're providing the "before", this PR is the "after". So it _shouldn't_ be working in your install, the fix isn't on `master` yet. All is well.

**Comment by DeeDeeG** [comment]
I'm gonna go ahead and merge on the basis of the approval from @confused-Techie, and anecdotal testing confirmation reported by @joshcangit, and my own personal testing.

Thanks for the reviews + comments, folks!

**Comment by Daeraxa** [comment]
Sorry thats my fault, for some reason I thought this had been merged already and I was commenting on it after the fact.

**Comment by DeeDeeG** [comment]
No worries @Daeraxa. 👍

**Pull request merged**
