### PR TITLE
Adds node-api and updates to fs-admin from 0.12 to 0.19

### PR DESCRIPTION
**Pull request by kaosine**
This updates to require node-api and fs-admin that should provide some performance boosts using the newer future looking node api. This should(?) provide some performance boosts using this newer node api(napi) and maybe make newer optimizations easier, I'd hope.

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
As long as this isn't causing conflicts anywhere else, modernizing is always good

**Review by DeeDeeG — APPROVED** [review]
Feels like I'm not supposed to review my own changes, but yeah! Looks good to me!

**Comment by kaosine** [comment]
Well yeah but it's a modernization that they seem to recommend. At least from my own searching so I pulled it figuring it'd help. Any updates to core dependencies we need asap XD

**Review by autumnblazey — COMMENTED** [review]
I have no idea what is going on in the code itself, but I definitely approve with switching to node-api

**Comment by DeeDeeG** [comment]
Brief context: I think fs-admin is mainly used to install the CLI commands? (Which only happens on end-user action and probably not too too often.) And even then only on macOS? The package is not even loaded unless those narrow circumstances. 

<details><summary>Code snippet in Atom where fs-admin is used</summary>

https://github.com/pulsar-edit/pulsar/blob/7f3f040628eb8f6d99a9619a5e70625cded6a182/src/command-installer.js#L86-L97

</details>

_(Also during development only, to install the built app if you give the `--install` flag to `script/build`.)_

So I think the stakes are pretty low.

Somehow someone decided that needs native C/C++ code???! Amd this used Node-API to do the native C++ code interfacing with Node/Electron, rather than NAN.

Other than that, I couldn't tell you how this is different from the older versions, honestly, other than by liking to the changelogs for people to review if they are interested:

https://github.com/atom/fs-admin/releases

And code comparison/commit log:

https://github.com/atom/fs-admin/compare/v0.15.0...v0.19.0

**Comment by autumnblazey** [comment]
so if I'm reading this correctly, `fs-admin`, is *only* used to install `atom` and `apm` to `/usr/local/bin` on macOS, full stop.

...

:0

**Comment by DeeDeeG** [comment]
Yeah, but only on macOS in the app itself, but only on Windows in `script/build`????????????????????????????????????

**Comment by autumnblazey** [comment]
nice

**Comment by autumnblazey** [comment]
If there are ways to get rid of this, I'm all for it

**Comment by DeeDeeG** [comment]
There are some unrelated docs updates that aren't really related to Pulsar.

Doesn't hurt to merge those also, I guess.

If folks don't mind, I will merge this soon, so atom-community's `master` branch doesn't update again and automatically change this PR again.

**Comment by autumnblazey** [comment]
for now yeah, I think its good

**Comment by kaosine** [comment]
Yeah going forward probably need to cherry pick stuff from them and cherry pick stuff to send back. I at least don't wanna seem like we're taking and not giving back. I know we differed from them on a good bit but some of our fixes might help XD

**Pull request merged**
