### PR TITLE
Adding a SQL State Storage instead of IndexedDB

### PR DESCRIPTION
**Pull request by mauricioszabo**
Will fix https://github.com/pulsar-edit/pulsar/issues/531

Needs:

* [x] Config info to toggle between state storages
* [ ] Some migration to the SQL version (so we don't lose things)
* [x] A way to "hot-swap" the storages when we toggle the config
* [ ] Tests - we need to drive this, because it's a BOLD change

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Does this need some more input from other folks? Is this ready for wider use? Would it be welcome for someone to grab a build of this branch and test a few things?

I don't mean to leave this PR open without responding to it, so seeing if I can be of help.

**Comment by mauricioszabo** [comment]
Yeah, I think the:

`Some migration to the SQL version (so we don't lose things)`

Can be done in a different branch :)

**Comment by mauricioszabo** [comment]
Translating: sure, let's merge it if it's ok with more people

**Comment by DeeDeeG** [comment]
I think I should test-drive this before moving to merge it.

Anything in particular I should try? Just loading up a bunch of windows with lots of tabs, and shutting down then reopening and reloading Pulsar a bunch of times? Open and close a lot of tabs, stuff like that?

**Comment by mauricioszabo** [comment]
Yes, @DeeDeeG, that's right. Don't forget to toggle the option in the config.

Although, I've been test-driving this for a while, and so far, I found no problems...

**Comment by DeeDeeG** [comment]
I found an issue using this branch's binary on macOS.

### Steps to reproduce:
- Grab binaries built from this PR (I grabbed them from here https://github.com/pulsar-edit/pulsar/actions/runs/7859594963 --> https://github.com/pulsar-edit/pulsar/actions/runs/7859594963/artifacts/1236161967)
- Extract zips somewhere so you have a bare `Pulsar.app`. Don't copy to `/Applications` folder, just leave it where it is.
- Ctrl + Click the binary and select "Open" to launch the Pulsar built for this PR.
- Don't update the "legacy session store" preference, leave it on "true" as the default.
- Open a new file, type some keyboard spam _including semicolons_ such as "as;ldka;sldka" into the new file. (Don't save this file, just write some keyboard spam into the "Untitled" new file and leave it open for now.)
- Command + Q to quit. When Pulsar asks you whether to save "Untitled", click "Don't Save". (Pulsar will quit.)
- Click on the Pulsar.app again to try and launch Pulsar.

### Expected:
- Pulsar should launch successfully.

### Actual (issue):
- An error "Error: Could not find module root given file: . . . Do you have a `package.json` file?"

<details><summary>Full error message and stack trace (click to expand):</summary>

```
index.js:83 Error: Could not find module root given file: "/private/var/folders/rd/9ccg_bdj4v949y62zjrcv9100000gn/T/AppTranslocation/DB1EBBAB-5A9A-46D9-95DD-62EE4404113E/d/Pulsar.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js". Do you have a `package.json` file? 
    at Function.getRoot (/private/var/folders…ngs/bindings.js:211)
    at bindings (/private/var/folders…ings/bindings.js:82)
    at Object.<anonymous> (/private/var/folders…qlite3-binding.js:1)
    at Object.<anonymous> (/private/var/folders…qlite3-binding.js:3)
    at Module._compile (/private/var/folders…ompile-cache.js:120)
    at Object.value [as .js] (/Applications/Pulsar…ompile-cache.js:252)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (/private/var/folders…compile-cache.js:67)
    at Object.<anonymous> (/private/var/folders…e3/lib/sqlite3.js:2)
    at Object.<anonymous> (/private/var/folders…/lib/sqlite3.js:209)
    at Module._compile (/private/var/folders…ompile-cache.js:120)
    at Object.value [as .js] (/Applications/Pulsar…ompile-cache.js:252)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (/private/var/folders…compile-cache.js:67)
    at Object.<anonymous> (/private/var/folders…tate-store/sql.js:3)
    at Object.<anonymous> (/private/var/folders…te-store/sql.js:119)
    at Module._compile (/private/var/folders…ompile-cache.js:120)
    at Object.value [as .js] (/Applications/Pulsar…ompile-cache.js:252)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    
handleSetupError | @ | index.js:83
```
</details>

Maybe Pulsar is looking for core Pulsar files in the wrong place, at the old stale "AppTranslocation" path from previous launch? (AppTranslocation dir is different every launch as a security measure for `.app`s launched from outside the `/Applications` dir, I think?

These steps to reproduce do not have the issue on Pulsar Rolling 115, and I think the issue doesn't happen if the "Untitled" file doesn't have any semicolons typed in it. So, maybe it's just a matter of escaping some semicolons, sanitizing inputs? Hmmm.

**Comment by mauricioszabo** [comment]
Seems like a `sqlite.js` NPM module error, really... maybe it's not finding the right directory for the SQLite binary...

**Comment by davidhealey** [comment]
Hi,

How do I enable this? I'm switching from the deb to the appimage and getting an error.

**Pull request merged**
