### PR TITLE
Decaffeinate (Part 2)

### PR DESCRIPTION
**Pull request by softcode589**
This "decaffeinates" some CoffeeScript code into JavaScript, **part 2**.

### CODE REVIEW

**Comment by softcode589** [comment]
cc @kaosine @confused-Techie can you review this PR? also core team

**Review by confused-Techie — CHANGES_REQUESTED** [review]
This looks great to me, the only concern is the `coffee.coffee` file. 

This file looks like its used for the tests on `compile-cache-spec.js` where the `CompileCache` is what decaffeinates files while the editor is running. So this may be the only CoffeeScript file we will have to leave in the editor. Unless we remove the feature entirely (But that would break a lot of packages)

So we should probably undo that instance of decaffeination and leave the file as is. But otherwise this looks good, and I'll just be interested to see how the tests turn out.

Thanks for the contribution!

**Comment by softcode589** [comment]
@confused-Techie and everyone reviewing, this is a WIP so don't merge this PR until I'm done

**Review by confused-Techie — APPROVED** [review]
While this is a draft PR, as it stands of the time of writing, it looks good to me and I'll approve.

The tests look good from our expected Test Failure Rate.

* Ubuntu 
  - Editor: 29
  - Package: 22
* Mac
  - Editor: Truncated
  - Package: 22
* Windows
  - Editor: Failed to Install 
  - Package: Failed to Install

**Comment by fabianfiorotto** [comment]
`spec/spec-helper.coffee` has already been decaffeinated in this PR https://github.com/pulsar-edit/pulsar/pull/50

**Comment by fabianfiorotto** [comment]
Most of the lines look as if they are taken directly from the compiler. We need to change them to remove the unneeded things in order to make the code more readable and easy to mantain. That includes

- Replace `var` with `const` and `let` if it's possible
- Replaced nested ternaries operators with `if` statements
- Remove `return` when it's not needed
- Remove result arrays when they aren't needed.
- Replace `for` loops with `for-of` loops
- Use arrow functions to write functions in a single line when it's possible
- Remove unneeded `ref` variables
- Remove [do](https://devdocs.io/coffeescript~1/index#loops) blocks and use let or const instead

**Comment by confused-Techie** [comment]
> Most of the lines look as if they are taken directly from the compiler. We need to change them to remove the unneeded things in order to make the code more readable and easy to mantain. That includes
> 
> * Replace `var` with `const` and `let` if it's possible
> * Replaced nested ternaries operators with `if` statements
> * Remove `return` when it's not needed
> * Remove result arrays when they aren't needed.
> * Replace `for` loops with `for-of` loops
> * Use arrow functions to write functions in a single line when it's possible
> * Remove unneeded `ref` variables
> * Remove [do](https://devdocs.io/coffeescript~1/index#loops) blocks and use let or const instead

Off topic I know, but this looks like some fantastic stuff to include in [`pulsar-edit/.github` PR#12](https://github.com/pulsar-edit/.github/pull/12)

**Comment by softcode589** [comment]
> Most of the lines look as if they are taken directly from the compiler. We need to change them to remove the unneeded things in order to make the code more readable and easy to mantain. That includes
> 
>     * Replace `var` with `const` and `let` if it's possible
> 
>     * Replaced nested ternaries operators with `if` statements
> 
>     * Remove `return` when it's not needed
> 
>     * Remove result arrays when they aren't needed.
> 
>     * Replace `for` loops with `for-of` loops
> 
>     * Use arrow functions to write functions in a single line when it's possible
> 
>     * Remove unneeded `ref` variables
> 
>     * Remove [do](https://devdocs.io/coffeescript~1/index#loops) blocks and use let or const instead

There is too much hassle, I do not seem to do this anytime soon. 8 tasks are too hard, so many are spec files and they are long. Ignoring the need.

**Comment by fabianfiorotto** [comment]
> There is too much hassle, I do not seem to do this anytime soon. 8 tasks are too hard, so many are spec files and they are long. Ignoring the need.

This is not an easy task. If so Atom team would have done it years ago.

**Comment by softcode589** [comment]
Closing this PR due to conflicts. Unfortunately, the funny thing is that I don't use Git, and these conflicts are too hard to resolve in the web editor. @pulsar-edit/core, you can rebuild this PR with @fabianfiorotto's suggestion and fix the merge conflict apparently.

**Pull request closed without merging**
