### PR TITLE
move bracket-matcher into repository

### PR DESCRIPTION
**Pull request by Sertonix**
This moves the `bracket-matcher` into the `packages` directory. I excluded the `CONTRIBUTING.md` and changed the `.gitignore` to `.npmignore`.

### CODE REVIEW

**Comment by confused-Techie** [comment]
While this is a good PR, is there anywhere we discussed expanding our core packages? I may have missed it, but is there a reason for this change?

**Comment by Sertonix** [comment]
This doesn't add bracket matcher as new core paclage it just moves the core package into the pulsar repository

**Comment by Sertonix** [comment]
This doesn't add bracket matcher as new core paclage it just moves the core package into the pulsar repository

**Comment by Sertonix** [comment]
Based on a [discussion on discord](https://discord.com/channels/992103415163396136/992109539346370661/1042602304509059102) I close this pull request.

**Pull request closed without merging**
