### PR TITLE
Running PR for Tree-sitter fixes

### PR DESCRIPTION
**Pull request by savetheclocktower**
This will be the new `tree-sitter-hell` PR. I'll add fixes as bugs get reported; we can merge this PR a few days before our next release goes out.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Correct me if I'm wrong, but does 4e52093cfcd050081710d1a0506528221194b2b2 resolve #576 ?

**Comment by savetheclocktower** [comment]
I think it fixes the part of that bug report that I actually think is a bug. I’ll look at it again tomorrow to be sure.

**Comment by savetheclocktower** [comment]
I marked this as ready for review so that we can get it properly looked at before 1.107. This fixes #559, #562, #575, #625, and #236, and also adds some features:

* ability for a theme to scope a JSON key differently from other strings, matching the TM-style JSON grammar's behavior
* implementation of the `parseCompletePromise` method that was present in the legacy `TreeSitterLanguageMode` class, and which some packages could've used to consume Tree-sitter trees; this makes it more likely that third-party packages that are Tree-sitter–aware will work seamlessly with the new modern Tree-sitter system
* ability for two different Tree-sitter parsers in the same package to share query files; this has limited applicability, but makes it much less of a pain to support two different Tree-sitter TypeScript parsers (one with JSX, one without)

**Review by confused-Techie — APPROVED** [review]
Changes here look great! (Even if the `scm` files are a bit over my head).

Glad to see new tests accompanying these changes, and can say that seeing the majority of these fixes pop up from issues being logged is awesome.

So while this is a total approval of these changes, without further modification, I wanted to ask would you feel comfortable adding the implementation of highlighting JSON keys within the default themes? I know this makes it possible to do so, but I didn't see any changes in the themes taking advantage of this.

Although if that feels out of scope that's totally fair

**Comment by savetheclocktower** [comment]
> So while this is a total approval of these changes, without further modification, I wanted to ask would you feel comfortable adding the implementation of highlighting JSON keys within the default themes? I know this makes it possible to do so, but I didn't see any changes in the themes taking advantage of this.

Yeah, I filed it as #597 and figured we'd discuss what the color should be in the various themes. I don't use any of the standard syntax themes, so I wanted the decision to be made by someone who did.

**Comment by confused-Techie** [comment]
@savetheclocktower Okay that sounds perfect to me then. Suppose as long as it stays on our radar, someone more familiar with those themes or dedicated to the idea could champion that change, rather than taking it on here. In that case, this looks good to me and is good to merge, of course considering the language changes, would be happy to see if @mauricioszabo had any thoughts

**Comment by savetheclocktower** [comment]
Sneaking in two quick fixes to the SCM files before I land this. CI was green, and these changes can't possibly break anything, so I won't wait around for the result.

**Pull request merged**
