### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by wlwl2**
Atom Github discussions are down/broken link. One-liner.

### CODE REVIEW

**Comment by confused-Techie** [comment]
Thanks for the contribution!

Although, considering our `CONTRIBUTING.md` in most repos we have been changing this to be in line with our current [guidelines](https://github.com/pulsar-edit/.github/blob/main/project-birth/CONTRIBUTING-DURING-START.md#contributingmd), and now we have a [`CONTRIBUTING.md`](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md) that is quite different from whats available here.

So question for @pulsar-edit/documentation, do we want to maintain the full contributing doc here? As in make this mirror whats available on `.github`? Or do we want to defer the document to `.github` and have this one look like all the others saying:

\[See how you can contribute\](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md)

What do we think?

**Comment by Daeraxa** [comment]
Personally I think it should be either a link to `.github` or hosted in the website readmes.

I think there is a discussion to be had whether the website should be "just" for application specific documentation or if it should be a home for everything related to project documentation.

**Comment by confused-Techie** [comment]
> Personally I think it should be either a link to `.github` or hosted in the website readmes.
> 
> I think there is a discussion to be had whether the website should be "just" for application specific documentation or if it should be a home for everything related to project documentation.

Yeah, I'm suggesting we go with just a link to `.github` and wasn't really considering the site. I think we could also host it on the site, but I'd like to see that these major files work without access to our site, if it were to ever go down, or someone were to consider our codebase without access to the internet.

**Comment by confused-Techie** [comment]
I know initially during this PR there was some discussion about if we wanted to change this file like this.

Since then the standard in every repo has been to link to our Org Documents. Like I suggested above, to instead remove all content of this file, and replace it with the following:

```markdown
[See how you can contribute](https://github.com/pulsar-edit/.github/blob/main/CONTRIBUTING.md)
```

Is this a PR you are still actively monitoring? Otherwise we can close it if needed.

**Comment by Spiker985** [comment]
@wlwl2 Closed due to staleness. This file also needs quite a bit more work than just that link. If you wish to continue this PR, or believe this to be an error, feel free to comment/reopen.

**Comment by wlwl2** [comment]
@confused-Techie @Spiker985 Sorry, I was in an army camp at that time for reservist. Thanks for closing it, I personally don't like doing tiny commits as well, but sometimes I have to.

**Comment by confused-Techie** [comment]
> @confused-Techie @Spiker985 Sorry, I was in an army camp at that time for reservist. Thanks for closing it, I personally don't like doing tiny commits as well, but sometimes I have to.

Thanks for getting back to us. But no worries at all, your contributions are always appreciated no matter what they are, hope to see more from you if time permits

**Pull request closed without merging**
