### PR TITLE
ppm: Update ppm to commit 0bc207133b26de82aa28500e

### PR DESCRIPTION
**Pull request by DeeDeeG**
Includes the following ppm Pull Request:
- https://github.com/pulsar-edit/ppm/pull/118

### CODE REVIEW

**Comment by DeeDeeG** [comment]
For the record, as a reminder of how to bump the submodule and do these ppm bumps:

- `git submodule update --remote ppm`
- `git add ppm`
- `git commit`

**Review by confused-Techie — APPROVED** [review]
LGTM! Thanks for putting this together!

**Comment by DeeDeeG** [comment]
I'll re-run tests. I'm surprised any of them failed, but they could just be flakes.

I'm okay if this merges without the tests being green, but I'll personally try and get them green real quick... (Of course the binary build takes a while, sigh.)

**Comment by DeeDeeG** [comment]
Yeah, I dunno what was up. Those CI jobs just said "This job has failed" and there were _no logs_. On just the macOS jobs on two different workflows. Weird.

They passed when re-ran. It's GitHub's problem, not mine to worry about!

Merging, thank you for the review!

**Pull request merged**
