### PR TITLE
add style to selected text by default

### PR DESCRIPTION
**Pull request by Sertonix**
Add a style for text selections by default. It doesn't make sense that it is not provided by default because a syntax variable is defined for it.

### CODE REVIEW

**Review by mauricioszabo — APPROVED** [review]

**Comment by mauricioszabo** [comment]
Maybe we can also document that now we have a style variable for selected text?

**Comment by Sertonix** [comment]
> Maybe we can also document that now we have a style variable for selected text?

This style variable is nothing new it just wasn't used before by default.

**Review by confused-Techie — APPROVED** [review]
Looks like this one has been sitting around for some time.

With an approval from @mauricioszabo and solid looking code I'll go ahead and approve as well and we can get it merged.

**Comment by DeeDeeG** [comment]
This isn't going to break existing themes, right?

Or will theme authors have an easy time working around this if it does?

**Comment by savetheclocktower** [comment]
My instinct is that it wouldn't; any theme that has already defined its own selection background styles won't have them overridden by this change, and I can't imagine any theme that would intentionally want selections not to look any different from ordinary text.

Haven't tested this change with my own custom syntax theme, but it seems logically sound.

**Comment by mauricioszabo** [comment]
Also, I just saw that we also have `atom-syntax-<dark|light>` bundled, do you want to also change on these packages?

**Comment by DeeDeeG** [comment]
@mauricioszabo good idea.

But if no reply here, we can perhaps do it as a follow-up to not block this, or if it is okay someone can upload the change of the rest of the bundled themes to this branch before merging?

**Comment by confused-Techie** [comment]
> @mauricioszabo good idea.
> 
> But if no reply here from the PR author, we can perhaps do it as a follow-up PR to not block this, or if it is okay someone can upload the change of the rest of the bundled themes to this branch before merging?

I'd be in favour of doing that as an additional PR if needed, since this one has been up for some time on it's own.

**Pull request merged**
