### PR TITLE
Icon in SVG

### PR DESCRIPTION
**Pull request by wincelau**
### Identify the Bug

A request of an SVG Icon https://github.com/pulsar-edit/pulsar/issues/62#issuecomment-1364568360

### Description of the Change

An SVG icon from PNG

### CODE REVIEW

**Comment by Digitalone1** [comment]
Thank you very much!

I parsed it with scour and made a smaller version (saved 28%).

If you want, you can replace it

pulsar-scour

**Comment by wincelau** [comment]
Ah yes thank you :+1: i replace it in the PR

**Comment by confused-Techie** [comment]
I wanted to add here, that while it might be a bit late we should have official SVG icons, not sure if that's what's being used here. And know it's already a working SVG, just wanted to make sure that's known

**Comment by Digitalone1** [comment]
> I wanted to add here, that while it might be a bit late we should have official SVG icons, not sure if that's what's being used here. And know it's already a working SVG, just wanted to make sure that's known

You could add this as temporary, waiting for the official one.

**Comment by Quantenzitrone** [comment]
image
really?
that's not how you make circles with svgs

also, there are some unclean spots in this svg (2 points really near to each other)
image

**Comment by Quantenzitrone** [comment]
i cleaned it up:
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg">
  <circle cx="64" cy="64" r="64" fill="#662d91"/>
  <g fill="#fff" stroke-width=".45233">
    <path d="m63.981 53.488c-5.7899 0-10.494 4.7043-10.494 10.494 0 5.7899 4.7043 10.494 10.494 10.494 5.7897 0 10.494-4.7043 10.494-10.494 0-5.7899-4.7043-10.494-10.494-10.494z"/>
    <path d="m51.089 78.41c0.36185 0.13574 0.72372 0.22616 1.0856 0.22616 0.72372 0 1.4022-0.2714 1.945-0.8142 1.0856-1.0856 1.0856-2.8497 0-3.9353-0.5428-0.5428-1.2665-0.8142-1.9903-0.8142-0.72374 0-1.4475 0.2714-1.9903 0.8142-0.8142 0.8142-1.0404 2.0354-0.58803 3.0306l-5.6089 2.1712-23.339 27.772 0.49756 0.49756 27.772-23.339z"/>
    <path d="m46.837 89.454c2.4427 2.0808 4.9305 3.9353 7.5539 5.6089 0.9499-0.36187 3.0306-1.1761 3.9353-1.7188-3.2115-1.8546-5.7899-3.7543-8.7301-6.2421z"/>
    <path d="m79.044 43.988-2.1712 5.6089c-0.36187-0.13574-0.72374-0.22616-1.0404-0.22616-0.72372 0-1.4022 0.2714-1.945 0.8142-1.0856 1.0856-1.0856 2.8497 0 3.9353 0.5428 0.5428 1.2665 0.8142 1.9903 0.8142 0.72374 0 1.4475-0.2714 1.9903-0.8142 0.8142-0.8142 1.0404-2.0354 0.58803-3.0306l5.6089-2.1712 23.339-27.772-0.49756-0.49756z"/>
    <path d="m75.469 45.436c-3.3472-2.0808-7.2826-3.3021-11.489-3.3021-12.032 0-21.847 9.8157-21.847 21.847 0 4.2066 1.2213 8.142 3.3019 11.489l1.1761-0.45234c0.18093-1.1761 0.72372-2.2616 1.5832-3.1664 0.18094-0.18093 0.36187-0.31664 0.58803-0.49756-1.0856-2.2165-1.7188-4.7494-1.7188-7.373 0-9.318 7.5992-16.917 16.917-16.917 2.6687 0 5.1565 0.63325 7.373 1.7188 0.13574-0.18093 0.2714-0.40709 0.45233-0.58803 0.85943-0.85942 1.945-1.4022 3.1664-1.5832z"/>
    <path d="m56.608 79.188c-0.13574 0.18093-0.2714 0.40711-0.45233 0.58803-0.85943 0.85943-1.945 1.4022-3.1664 1.5832l-0.45234 1.1761c3.3472 2.0808 7.2826 3.3021 11.489 3.3021 12.032 0 21.847-9.8157 21.847-21.847 0-4.2066-1.2213-8.142-3.3019-11.489l-1.1761 0.45233c-0.18093 1.1761-0.72372 2.2616-1.5832 3.1664-0.18094 0.18094-0.36187 0.31664-0.58803 0.49756 1.0856 2.2165 1.7188 4.7494 1.7188 7.373-0.0453 9.3633-7.6445 16.917-16.962 16.917-2.6684-3.76e-4 -5.1562-0.63365-7.3727-1.7192z"/>
    <path d="m27.976 93.745 2.3974-2.8497c-3.2568-5.9255-3.2568-13.932-0.40711-22.391 2.2616 4.3877 5.1565 8.6848 8.5943 12.665l2.3069-2.714c-3.8449-4.5686-6.9206-9.4537-9.1371-14.429 2.8949-6.5136 7.373-13.072 13.299-18.997 5.7899-5.7899 12.303-10.313 18.953-13.299 4.8852 2.1712 9.8157 5.2018 14.475 9.1371l2.714-2.3069c-4.0709-3.483-8.4133-6.3327-12.711-8.549 1.4474-0.49756 2.8497-0.90465 4.2519-1.2213 7.1468-1.6284 13.389-1.0404 18.183 1.5832l2.8497-2.3974c-5.6542-3.6187-13.253-4.5686-21.803-2.6236-2.6687 0.58802-5.3375 1.4474-8.0062 2.5782-12.937-5.2922-25.601-4.7043-33.156 2.8497-5.835 5.835-7.78 14.836-5.428 25.285 0.58803 2.6687 1.4927 5.3375 2.5784 7.9611-4.5231 11.127-4.7492 22.074 0.0455 29.718zm31.527-63.779c-5.9708 3.0759-11.806 7.3277-17.008 12.575-5.2922 5.2922-9.4989 11.127-12.53 17.008-0.45232-1.4022-0.90465-2.8044-1.2213-4.2519-2.0354-9.2729-0.45233-17.098 4.4784-22.028 5.971-5.9709 15.787-6.8304 26.28-3.3021z"/>
    <path d="m83.025 82.935c-8.3228 8.3228-18.139 14.067-27.682 16.239-7.1468 1.6284-13.389 1.0404-18.183-1.5832l-2.8497 2.3974c3.7543 2.3974 8.3228 3.6187 13.434 3.6187 2.6687 0 5.4733-0.31664 8.3682-0.99513 10.177-2.3069 20.626-8.3681 29.402-17.144 5.1565-5.1565 9.4537-10.992 12.575-17.008 3.5283 10.494 2.6687 20.31-3.3019 26.28-4.5233 4.5233-11.625 6.197-19.813 4.8852-1.5379 0.94989-3.0759 1.8093-4.659 2.5782 3.483 0.90467 6.8302 1.4022 9.9512 1.4022 6.8755 0 12.801-2.1712 17.008-6.3778 10.946-10.946 7.2826-32.703-7.78-50.39l-2.3531 2.715c3.89 4.659 6.9659 9.6079 9.1371 14.448-2.9853 6.6493-7.5991 13.28-13.253 18.935z"/>
    <path d="m97.59 37.113c1.9903 3.6638 2.7593 8.2324 2.3069 13.344 1.0404 1.6284 1.9903 3.3021 2.8044 4.9305 1.7188-8.2777 0.76898-15.605-2.7593-21.168z"/>
  </g>
</svg>
```

**Comment by confused-Techie** [comment]
So I wanted to mention, earlier up I mentioned we have an SVG icon, so we don't have to create a new one here if we don't want to.

Additionally is this intended to only be within the repo itself? Since as it is now it likely wouldn't be package into any application binaries.

**Comment by Daeraxa** [comment]
Was this icon generated from our actual original SVGs or was it traced from the PNG?

**Comment by Digitalone1** [comment]
> Additionally is this intended to only be within the repo itself? Since as it is now it likely wouldn't be package into any application binaries.

I'd like to add it in the build folder to make it as desktop icon on Linux (from a post install script).

**Comment by Digitalone1** [comment]
> Was this icon generated from our actual original SVGs or was it traced from the PNG?

Can you link it? As far as I remember, the only SVG icon was the one on the website which does not have the purple circle behind the main symbol.

**Comment by Quantenzitrone** [comment]
the dirtyness also occurs in the svg with no purple circle on the website :/

**Comment by Quantenzitrone** [comment]
https://pulsar-edit.dev/logo-only-light.svg

who does these svgs:
- there is an unneeded transform attribute on everything in the svg
- the viewbox is 50.774 x 50.721 which IS NOT EVEN SQUARE
- every path has a class attribute of "st0 class1" which has no definition

other minor things increasing the file size:
- unneeded IDs on every object
- color attribute is in `rgb(255, 255, 255)` instead of just `#fff`

**Comment by Digitalone1** [comment]
@Quantenzitrone Open an issue [here](https://github.com/pulsar-edit/pulsar-edit.github.io/issues) and propose your version.

Anyway, speaking of useless tags, also the first xml one is unneeded, along with the version attribute in svg.

**Comment by Daeraxa** [comment]
> who does these svgs:

I really wouldn't read too much into it yet. We got the original SVGs from the designer but the ones we have been using have been hastily converted or added just to get *something* on the website etc. whilst we wait for our actual branding colours etc. to be finalised.

**Comment by Daeraxa** [comment]
> Can you link it? As far as I remember, the only SVG icon was the one on the website which does not have the purple circle behind the main symbol.

There is a `logos.zip` pinned to the #rebrand channel

**Comment by confused-Techie** [comment]
Additionally to avoid having to search the rebrand channel, I've now started a PR to put all of our iconography into the `.github` repo so it's easier to find without searching Discord. Just take a look at the [PR](https://github.com/pulsar-edit/.github/pull/111) and it includes the actual SVG from our designer (as well as many other icons) but hopefully can be merged soon

**Comment by wincelau** [comment]
> Was this icon generated from our actual original SVGs or was it traced from the PNG?

I started from this one https://pulsar-edit.dev/logo-name-navbar-light.svg and I added the circle and adjusted the size with inkscape with the png in background for the placements

**Comment by confused-Techie** [comment]
> > Was this icon generated from our actual original SVGs or was it traced from the PNG?
> 
> I started from this one https://pulsar-edit.dev/logo-name-navbar-light.svg and I added the circle and adjusted the size with inkscape with the png in background for the placements

So while I appreciate the work you went to to create this icon. We do have an official one from the designer.

It was previously in our Discord, but because of all the concern here I'm uploading it to [`.github`](https://github.com/pulsar-edit/.github/pull/111) in a PR, and the actual file is currently accessible via [this](https://github.com/pulsar-edit/.github/blob/a3c4c56ad8b12e827368c6bfa51d421fdd987000/pulsar-iconography/generic-icons/generic_reference/pulsar.svg) link. (Again that link is to the file within the PR, and will likely not be valid once the PR is merged)

**Comment by wincelau** [comment]
Okay

I replace the version from @Quantenzitrone with the circle optimisation (thank you) in this PR

**Comment by wincelau** [comment]
> > > Was this icon generated from our actual original SVGs or was it traced from the PNG?
> > 
> > 
> > I started from this one https://pulsar-edit.dev/logo-name-navbar-light.svg and I added the circle and adjusted the size with inkscape with the png in background for the placements
> 
> So while I appreciate the work you went to to create this icon. We do have an official one from the designer.
> 
> It was previously in our Discord, but because of all the concern here I'm uploading it to [`.github`](https://github.com/pulsar-edit/.github/pull/111) in a PR, and the actual file is currently accessible via [this](https://github.com/pulsar-edit/.github/blob/a3c4c56ad8b12e827368c6bfa51d421fdd987000/pulsar-iconography/generic-icons/generic_reference/pulsar.svg) link. (Again that link is to the file within the PR, and will likely not be valid once the PR is merged)

It's cool that you found the original version, it differs a bit from the png (resources/pulsar.png), but I find it better balanced.

On the other hand the svg does not contain only the logo it is with other elements of the graphic charter (you can see it by opening it in inkscape).

I have extracted it if you want to get it: https://github.com/pulsar-edit/pulsar/pull/275/files

Its size is 2,4 kb instead of 53,4 kb

**Comment by wincelau** [comment]
Or here :

**Comment by confused-Techie** [comment]
Thanks @wincelau for this variant, I'm adding it to the PR

**Comment by Digitalone1** [comment]
@confused-Techie after the merge of #327, this can be closed.

**Comment by joshcangit** [comment]
I'd want to also add that the icon is not showing when I install the package.

Creating the **0x0** folder never worked.

The current png icon is 1024px so placing it under the **1024x1024** folder will have it show only when the icon is at that resolution.

Since you're suggesting to use svg, maybe put that under the **scalable** folder.

You can refer to this website for placing the icon.
<https://martin.hoppenheit.info/blog/2016/where-to-put-application-icons-on-linux/>

**Comment by confused-Techie** [comment]
As PR #327 is now merged, I'll go ahead and close this one.

I appreciate the contributions and work that went into this PR and I'm glad we could get the issue resolved! Thanks to everyone!

**Pull request closed without merging**
