### PR TITLE
[language- && packages] Manual Decaf Spec Bundle

### PR DESCRIPTION
**Pull request by confused-Techie**
This PR aims to near full completion on decaffing all `spec`s within this repo, save for a few more complex cases, or larger core packages.

No big liberties are being taken with decaf work, due to it's shear size, the focus is on the minimum amount of steps needed to make more readable JavaScript, and more universal changes, rather than stylizing each file and function.

This PR decafs the following specs of the following packages: (Checkboxes to indicate how long till this PR is out of draft status)

- [X] `language-html`
- [X] `language-hyperlink`
- [X] `language-java`
- [X] `language-javascript`
- [X] `language-json`
- [X] `language-less`
- [X] `language-make`
- [X] `language-mustache`
- [X] `language-objective-c`
- [X] `langauge-perl`
- [x] `language-php`
- [x] `language-python`
- [x] `language-ruby`
- [x] `language-ruby-on-rails`
- [x] `language-sass`
- [x] `language-shellscript`
- [x] `language-sql`
- [x] `language-text`
- [x] `language-todo`
- [x] `language-toml`
- [x] `language-xml`
- [x] `language-yaml`
- [x] `wrap-guide`
- [X] `deprecation-cop`
- [X] `autoflow`
- [x] `autocomplete-atom-api`

### CODE REVIEW

**Comment by confused-Techie** [comment]
This PR is now ready to review, keep in mind while the diff is still being compared to our machine decaf branch the Codacy checks will always fail.

Once this PR is ready to be merged the base branch will be changed to `master` which makes the diff unreadable, but will allow tests to properly run against our current environment.

> This PR relates to #444

**Comment by confused-Techie** [comment]
Alright I'm gonna go ahead and change the base branch on this one.

As there are zero code changes from the manual decaf work, and I know nobody is too keen on reviewing these ones.

If tests pass after changing the branch I'll go right on ahead and merge.

**Review by DeeDeeG — COMMENTED** [review]
I don't have time to really review, but I understand the reasoning why these usually end up merged un-reviewed.

I will say this: If something breaks and you want another set of eyes on fixing it, I'll try and dedicate some time to that. Otherwise, most of these decafs have gone pretty smoothly, and it's nice having one less thing (CoffeeScript) to think about!

I can't do like a full approve since I haven't reviewed it, but I am supportive of these efforts! 👍 So, not to cross the wires on meanings, but I in that sense I am informally _approving_ toward this and all the other decafs that have gone so well so far.

I suppose my point is to say I've seen this and will lend supportive efforts where I can should this need anything post-merge. And so on like that.

**Comment by confused-Techie** [comment]
@DeeDeeG thanks a ton for taking a quick peek at this, even if not a full review.

I do appreciate it, and exactly these are rather boring PRs, and since I've stopped doing any kind of refactors of any code during these changes, things have become very smooth so far in these, so I don't worry to much about merging without a review. 

But I'll make sure to ping you if needed, I'm thinking these specs ought to be rather simple, but we do have the last few slightly more complicated decafs to do after this.

---

With all the above said, tests are now passing so I'll go ahead and merge this one, thanks again!

**Pull request merged**
