### PR TITLE
Trying to fix windows builds

### PR DESCRIPTION
**Pull request by mauricioszabo**

### CODE REVIEW

**Review by confused-Techie — DISMISSED** [review]
Sorry for lag on review for this one.

But I assume this would help the fact that in nearly all tests Windows just fails to install. And in that case approve getting this on master.

**Comment by mauricioszabo** [comment]
@confused-Techie I actually never got it working on Windows :(

**Comment by confused-Techie** [comment]
> @confused-Techie I actually never got it working on Windows :(

Bummer to hear. Is there any value in this PR then or should it be closed?

**Comment by mauricioszabo** [comment]
I think I'll convert it to `draft` and then just re-use the branch to try different things. If I somehow can make things work, I'll rebase the commits

**Comment by confused-Techie** [comment]
> Wait, I can't convert to Draft?

Its got the work-in-progress tag, so it should be known not to commit without further review.

**Comment by confused-Techie** [comment]
Since Windows builds are now working should we go ahead and close this PR?

**Comment by Spiker985** [comment]
@mauricioszabo Is this still needed?

**Comment by Spiker985** [comment]
Closing as a _lot_ has gone on in this space, and this is wildly out of date now

**Pull request closed without merging**
