### PR TITLE
Updated README Design

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Separator]: https://raw.githubusercontent.com/ElectronicsArchiver/ElectronicsArchiver/%E3%83%97%E3%83%AD%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB/Separator.png

[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｃｏｍｍｅｎｄａｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<div align = center>

![Separator]

<br>
<br>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

<br>

*I adjusted my design a bit to be easier on the eyes~*

<br>

</div>

## ![Badge Changes]

- Removed old, duplicate & unused badge declaration.

- Adjusted badge colors to 

  - reduce the contrast between the badge title and content.
 
  - to increase the constrast between background and badge title.

  - to comply with the given color palette.

- Adjusted layout to be more inline with the common, user expected, 
  `social media at the top navigation below` concept.

<br>
<br>

## Release Notes

N/A

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

<div align = center>

## ![Badge Robot]

<br>

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

![Separator]

</div>

[Preview]: https://github.com/ElectronicsArchiver/pulsar

### CODE REVIEW

**Comment by confused-Techie** [comment]
Yeah I agree with @Daeraxa it might be best to wait before we start modifying colours and such.

The layout is a great suggestion, and removing duplicates obviously also great. But beyond that the cards are all already being changed, and really I'd think we want the colours to match our branding once we have that rather then least contrast.

As always thanks for the contribution, but maybe lets get #120 merged first, if you'd like to contribute on that, then we can modify what that's already doing

**Comment by confused-Techie** [comment]
With #120 having been merged do we feel this PR is still needed? Or would @ElectronicsArchiver want to rebase, and change the new badges that have been added?

**Comment by ElectronicsArchiver** [comment]
Thanks GitHub for not notifying me at until now . . .

**Comment by confused-Techie** [comment]
> Thanks GitHub for not notifying me at until now . . .

No worries, but feel free to let me know what you'd like to do on this PR. Again thanks for contributing!

**Comment by ElectronicsArchiver** [comment]
> With #120 having been merged do we feel this PR is still needed? Or would @ElectronicsArchiver want to rebase, and change the new badges that have been added?

Guess I can rebase~

**Comment by ElectronicsArchiver** [comment]
@confused-Techie Done

**Review by confused-Techie — APPROVED** [review]
This PR looks great, with the changes you've added and referencing how it looks [displayed](https://github.com/ElectronicsArchiver/pulsar) as a ReadMe, looks great to me.

Now of course keep in mind eventually these colours will likely be changed, and we will have to find the best location for the social links to go once a banner is here. But otherwise looks great to me, and I say lets merge this one. If anyone else from @pulsar-edit/documentation wants to take a look first

**Comment by confused-Techie** [comment]
So I'm looking at this PR and wanting to merge it, but it's showing changes to PPM. Which obviously as this PR is for the readme, we should address before merging.

I was wanting to go ahead and get this fixed, which with your permission is something I'll do, unless you'd like to do it yourself.

As we haven't come across this issue before, we are trying to determine what exactly needs to be done to get the submodule to match what's present in our repo, but feel free to read our [discussion](https://discord.com/channels/992103415163396136/992103415163396139/1043749072638574642) on it, to find the right command to run, or otherwise let me know if it's fine to try myself.

Thanks again for your contribution!

**Comment by DeeDeeG** [comment]
Hi folks, I do have a commit that should resolve the ppm situation: https://github.com/pulsar-edit/pulsar/compare/master...DeeDeeG:pulsar:erpm-ppm-fix (be968b79bf2931d715f33958d13a46337a5c27c0). So this is technically figured out, just want to make sure we communicate properly about how to get it in as a part of this PR. (See @confused-Techie's comment above.)

**Comment by ElectronicsArchiver** [comment]
@confused-Techie I don't have Discord, can't access the discussion even if I wanted.
I activated maintainer editing permission.

**Comment by confused-Techie** [comment]
@DeeDeeG looks like the best move might be to commit those changes you made if you wouldn't mind.

Thanks for letting us get this sorted @ElectronicsArchiver

**Pull request merged**
