### PR TITLE
Decaf `wrap-guide`

### PR DESCRIPTION
**Pull request by confused-Techie**
So this PR is a bit of a smaller one, some simple decaf work for the package `wrap-guide`.

As always this PR is targeting a branch `wrap-guide-decaf` that has been machine decaffed for easier review.

If this PR is accepted, prior to being merged, the target branch will change to main and will be merged into the editor.

Please feel free to provide any feedback!

A few notes here, some of the awkward return function patterns were left in to be reworked later in a more focused PR, since they do work, and the fix isn't immediately known. Additionally within `wrap-guide-element.js` on Line 32, there is a `TODO` once it's converted to JavaScript. I'll take a further look, since I'm unsure of which portion should be changed, but I'm assuming it's the API call itself to `getNextUpdatePromise()` but will try to investigate further later on.

### CODE REVIEW

**Comment by confused-Techie** [comment]
So on this:

* `find-and-replace`: 45 Failures ✅
* `settings-view`: 1 Failure ❌ (But we are seeing this repo wide, and has no bearing on this PR)
* `symbols-view`: 2 Failures ✅
* `tree-view`: 2 Failures ✅

So tests look good, looks like this decaf went without any issues

**Comment by confused-Techie** [comment]
If anyone wants to give this a review it'd be very appreciated

**Review by Spiker985 — COMMENTED** [review]
It all reads properly. The single `}` on L187 is correct, yeah? (reviewing on mobile - it's a pain to make sure brackets match across long swaths of code)

And I assume no spec changes (at this time), because otherwise how would we know if the decaff broke anything, right?

**Comment by confused-Techie** [comment]
@Spiker985 Yup zero spec changes, and that single `}` is because the whole class was originally wrapped in `()` rather than being normally declared. So that last bracket is the end of a class definition. And all tests are still passing, thanks a ton for giving such a speedy review!

**Review by Spiker985 — APPROVED** [review]

**Comment by confused-Techie** [comment]
@Spiker985 thanks for your approval!
With that and passing specs, I'll go ahead and merge this one!

**Pull request merged**
