### PR TITLE
Add options for [skip-ci], [skip-editor-ci], and [skip-package-ci] on PR

### PR DESCRIPTION
**Pull request by Spiker985**
Allow skipping tests when not required, for example, when only making changes to MD files.

The conditions are only set up to skip during the `pull_request` event. What that means in practice, is that the workflows will still execute when you merge a PR, regardless of whether the title starts with one of the 3 options above

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
This looks great to me. And also love that this can cut down on the many tests that are created for every single PR. And lets us be a little nicer to GitHub's servers.

The only thing I'd recommend is, either adding it to this PR, or additionally opening a PR on our website, or really somewhere to add the documentation about this.

Maybe we even just add it to the PR template?

**Comment by Spiker985** [comment]
@confused-Techie Added PR https://github.com/pulsar-edit/.github/pull/54 to coincide

**Comment by Spiker985** [comment]
@pulsar-edit/core Can we have someone else review this PR?

**Review by mauricioszabo — APPROVED** [review]
It always amazes me how many commits do we need to fix CI things, because CI's syntaxes are always quite crazy :D

Anyway, LGTM

**Pull request merged**
