### PR TITLE
Tree-sitter running fixes

### PR DESCRIPTION
**Pull request by savetheclocktower**
This is another draft PR containing running Tree-sitter fixes. It should be landed before 1.108.

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
Always love these bundle of fixes PRs, lets get it merged!

**Comment by confused-Techie** [comment]
Although prior to merge we should probably make sure we can see the rest of the builds passing, since they don't seem to be happy here

**Comment by savetheclocktower** [comment]
Just realized the content of #660 is also present here. Reverting those commits for simplicity's sake.

**Comment by AlexWayfer** [comment]
> Just realized the content of #660 is also present here. Reverted those commits for simplicity's sake.

This PR is actually #660. 🤨

**Comment by savetheclocktower** [comment]
Eh, whatever. #659. Just be glad I'm even _endeavoring_ to explain my actions.

**Comment by AlexWayfer** [comment]
> Eh, whatever. #659. Just be glad I'm even _endeavoring_ to explain my actions.

It was not a claim, just for history and clarity. Thanks.

**Pull request merged**
