### PR TITLE
Update changelog entries for 1.112.1

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Description of the Change

- Update release note entry for the first `ppm publish` fix, for more accuracy
- Add pull request links for the second round follow-up fix for the first `ppm publish` fix

### CODE REVIEW

**Comment by DeeDeeG** [comment]
This assumes #845 merges. So, marked as a draft until then.

**Review by confused-Techie — APPROVED** [review]
Approving as is, but if theres time, I'll add that I usually add the newest commits at the top of the file, going down in chronological order.

But at the end of the day it's not that important. So this approval applies woth or without that change

**Comment by DeeDeeG** [comment]
> I usually add the newest commits at the top of the file, going down in chronological order.

Done.

Was waiting on the `ppm` CI re-runs to finish, so I took the opportunity to invert the order of the changelog entries as you suggested. 👍

**Comment by DeeDeeG** [comment]
The changes look so sparse in `packages/welcome/lib/changelog-view.js`...

Should we link to or at least mention there are full release notes for 1.112.0 as well? Since there was a lot that changed that many people won't see in the in-app changelog, otherwise, just because we did a patch release.

**Comment by DeeDeeG** [comment]
Alright, thanks for the review! going to go ahead and merge this now, and get the binaries going!

**Pull request merged**
