### PR TITLE
Fix Linux Desktop Icon

### LINKED ISSUE #179: [Very Minor] No Icon in Window List
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When Pulsar is installed and run, no icon appears in the window list in the panel, nor in the menu.

I tried making a custom launcher and specified the pulsar.png icon. While this gave it an icon on the desktop (and when _that_ was added to the menu there was an icon) it still doesn't appear in the Window list.

As I said, very minor but is probably some "polish" needed before the official release.

Thanks for all your hard work, I'm glad to be running Pulsar so I really appreciate it.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 1 (Cinnamon 5.4.12)

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install from latest .deb
2. Run the app

### Additional Information:

_No response_

### LINKED ISSUE #261: Wrong icon path in Linux builds
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

The icon path in Linux build is `/usr/share/icons/hicolor/0x0/apps/`. This is wrong and prevent the icon to be shown in applications menu or desktop docks.

The right one is `/usr/share/icons/hicolor/scalable/apps/`.

Fortunately the AUR package has been patched to fix this, but it should be fixed here anyway and I'd like to point out that because of the details shown [here](https://github.com/pulsar-edit/pulsar/issues/62#issuecomment-1364567929) the actual PNG icon is not optimal.

Can we make an SVG version to be used in its place and bundle in inside the Linux builds? Thanks. @kyjus25

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Arch Linux

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install a Linux build
2. The app icon is not showing 

### Additional Information:

https://github.com/pulsar-edit/pulsar/issues/62#issuecomment-1364567929

### PR DESCRIPTION
**Pull request by Digitalone1**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see <https://flight-manual.atom.io/hacking-atom/sections/writing-specs/>.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/atom/.github/tree/master/CONTRIBUTING.md#pull-requests>.

### Identify the Bug

- https://github.com/pulsar-edit/pulsar/issues/62#issuecomment-1364567929
- Fixes #261 
- Fixes #179 

### Description of the Change

This PR intends to fix the missing Pulsar desktop icon under Linux OS. I call it **desktop icon** since lots of confusion was made about it when I announced to adopt an SVG icon. I know that electron does not support SVG icons and this PR does not want to include this format in the executable.

The PR wants to fix the icon that is managed by desktops on Linux to be shown in app switcher/bar and app menus, which can be in PNG, but also SVG is supported.

At the moment a bug in electron-builder is preventing the icon to be installed in the proper path (under `/usr/share/icon/...`), so it's not shown by the desktop.  Thanks to @jonian it's temporarily fixed on the AUR package, but we want to fix it in the building stage having package formats (deb/rpm/appimage/flatpak) in a correct state.

Besides, since electron-builder has some limitations, SVG desktop icons cannot be properly installed in the proper places, so the idea here is to include an SVG icon in a way that it does not harm the correct execution of electron and at the same time packagers have a chance to move it in the right place (similarly as it has been done with the AUR fixing the wrong path). This way different PNGs and one SVG are shipped as desktop icons like some applications such as Firefox are currently doing on Linux. 

So this PR:
- adds various PNG icons provided by @confused-Techie to `resources/icons` in order to make electron-builder to generate the proper paths (it seems that providing only one icon to electron-builder causes the above mentioned bug, but providing a folder with multiple icons which specify the size in their name lead to a correct behavior).
- adds an SVG icon under `opt/Pulsar/resources` which can be managed by packagers (if they want) to be added under `usr/share/icons/...` folder to be used as desktop icon alongside the other ones.

Thanks to @wincelau and @Quantenzitrone to the contribution for the SVG icon. The SVG version by @confused-Techie has been used anyway.

### Alternate Designs

No alternate designs because, at least for PNG icons, this seems the only way to generate correct desktop icon paths by electron-builder. 

### Possible Drawbacks

The SVG under resources folder could harm the correct execution of the whole application. This has to be tested, but didn't have to opportunity to do it locally. I hope the builds made by Cirrus will make me test this in a proper way. If the SVG is a problem, we have to give up and not include it, relying only in PNGs.

### Verification Process

As stated above, will thy the builds by Cirrus.

### Release Notes

- Fixed desktop icons path in Linux builds

### CODE REVIEW

**Comment by Digitalone1** [comment]
Okay, downloaded the deb package, installed it with a custom PKGBUILD and it's working. The PNG icons are in the right places. The SVG icon in resources is not causing any harm.

@confused-Techie can you look why the window build is failing on cirrus?

Besides, even if the icon is showing on the dock, it has margins that make it look smaller.

Schermata del 2023-01-09 18-01-53

But that's my bad, I chose the wrong ones, there are also versions without margins, I'll replace them.

@confused-Techie can you make also PNG versions of 64, 128 and 192 px? Thanks.

Also, can we wait for the next release until this is merged?

**Comment by confused-Techie** [comment]
> Okay, downloaded the deb package, installed it with a custom PKGBUILD and it's working. The PNG icons are in the right places. The SVG icon in resources is not causing any harm.
> 
> @confused-Techie can you look why the window build is failing on cirrus?
> 
> Besides, even if the icon is showing on the dock, it has margins that make it look smaller.
> 
> Schermata del 2023-01-09 18-01-53
> 
> But that's my bad, I chose the wrong ones, there are also versions without margins, I'll replace them.
> 
> @confused-Techie can you make also PNG versions of 64, 128 and 192 px? Thanks.
> 
> Also, can we wait for the next release until this is merged?

I'll absolutely get these done after work today.

And I bet it seems we are likely doing the next release sometime this week, so we likely could. Just have to make sure we get the entries into the ChangeLog PR, which luckily is still open

**Comment by Digitalone1** [comment]
Fixed.

Schermata del 2023-01-10 18-42-21

And now the icon is not bad scaled in the switcher.

Schermata del 2023-01-10 18-43-36

**Comment by confused-Techie** [comment]
@Digitalone1 I've gone ahead and updated my PR to contain all icons needed for Linux.

So you should just be able to take everything from there, knowing they all will have the proper borders, and centering applied.

**Comment by confused-Techie** [comment]
@Digitalone1 Just fyi, before adding all of the files I've newly created, take a look at `#rebrand` on the server, looks like those may get changed again, I apologize for any confusion

**Comment by Digitalone1** [comment]
> @Digitalone1 Just fyi, before adding all of the files I've newly created, take a look at `#rebrand` on the server, looks like those may get changed again, I apologize for any confusion

When the definitive version is ready and you add it, I will export them on this branch.

**Comment by confused-Techie** [comment]
> > @Digitalone1 Just fyi, before adding all of the files I've newly created, take a look at `#rebrand` on the server, looks like those may get changed again, I apologize for any confusion
> 
> When the definitive version is ready and you add it, I will export them on this branch.

This sounds perfect! Thanks for keeping an ear out

**Comment by Digitalone1** [comment]
@confused-Techie @DeeDeeG Added new icons from new SVG versions.

**Comment by bobemoe** [comment]
Confirmed its fixed the icon in Xfce4 Whisker menu on Devuan (Debian) Linux:

Before  After

**Comment by bobemoe** [comment]
I suspect this also fixes: https://github.com/pulsar-edit/pulsar/issues/179

**Comment by Digitalone1** [comment]
> I suspect this also fixes: #179

Thanks. Added to the open post. Will close when merged.

**Review by confused-Techie — APPROVED** [review]
While we want to have finalized icons here, we can always modify it later, lets get this merged as it fixes issues users are experiencing, and get our next release up!

**Comment by DeeDeeG** [comment]
Thank you very much @Digitalone1 for working through this, and any others who helped point out the problem and contribute to this issue in various ways.

Happy to have the technical fix sorted.

**Pull request merged**
