### PR TITLE
Add the Tree-sitter Markdown grammar

### PR DESCRIPTION
**Pull request by savetheclocktower**
### Description of the Change

This PR adds a modern Tree-sitter grammar for Markdown files to the `language-gfm` package. It also updates the eight built-in syntax themes so that there are no arbitrary highlighting differences between the existing TM-style Markdown grammar and the new grammar.

I’ve been using this new grammar for months and I _love_ it. There are two different `tree-sitter-markdown` parsers out there; [one of them](https://github.com/MDeiml/tree-sitter-markdown) is bleeding-edge and ambitious, and [one of them](https://github.com/ikatyang/tree-sitter-markdown) is weird and seemingly unmaintained.

I went for the latter because, unmaintained though it seems to be, it is _practically bulletproof_ at the workmanlike job of parsing Markdown. The newer and more active parser might be worth switching to eventually, though it’s got its own quirks (a two-pass parsing system that would require an injection in _every_ block-level Markdown structure). But right now it’s just too buggy to consider.

The only thing preventing me from contributing this grammar earlier was the `ikatyang` parser’s complete lack of support for YAML front matter — the incredibly common construct [popularized by Jekyll](https://jekyllrb.com/docs/front-matter/) and adopted by a whole bunch of static site generators.

I tried some hacky ways of shoehorning front-matter support into the grammar before I just gave up and wrote my own [Tree-sitter parser to understand front matter](https://github.com/savetheclocktower/tree-sitter-frontmatter). Once I got that parser working, the rest was easy: the front matter parser’s only job is to identify and isolate any front-matter section in the file, putting all non-front-matter content into a single node into which I can inject the `tree-sitter-markdown` parser.

The result: **front matter support!**

Screenshot 2023-07-30 at 11 58 35 PM

### Upsides

What does this parser give us that the old parser doesn’t?

* It’s incredibly correct about a lot of things. It can identify pretty much all Markdown constructs to an astounding degree of accuracy; the TM-style parser didn’t ever really try to do that.
* It’s not universally known that Markdown is a superset of HTML — it’s designed so that you can ignore the abstractions and write plain HTML whenever you need to. The TM-style grammar ignores this completely, but `tree-sitter-markdown` supports it, both for block-level HTML constructs and inline HTML:

    Screenshot 2023-07-30 at 11 26 01 PM

* Introducing a new parser is a great opportunity to introduce more conventional scope names and move away from the naming conventions of the old grammar — which were clearly chosen by someone who hadn’t ever read much about scopes.

### Alternate Designs

I explained above why I chose the parser that I chose, and why I wrote a whole other parser just so I could use the first one.

### Possible Drawbacks

I’m not sure. I’ve tried to ensure that there won’t be any visual regressions, but people who use third-party syntax themes might notice the changes.

There are a few GitHub-specific constructs that aren’t recongized by the new parser: specifically at-mentions and issue references. I don’t think these will be missed; but if people feel differently, we could write yet another Tree-sitter parser to inject into paragraphs that look like they might have an at-mention or an issue reference.

Code folding should be roughly equivalent. I have hopes that one day I’ll be able to make the fold system robust enough that I could treat headings as fold markers; so that if you were to fold an `h2` heading, it’d collapse all the content until the next `h2` heading. But we’re not quite there yet.

### Verification Process

Do as I’ve done in the screenshot: open your favorite Markdown file in two editors side by side — one using the new grammar and one using the old one. The only visual differences you’ll notice ought to be improvements.

### Release Notes

* Added a modern Tree-sitter grammar for Markdown files.

### CODE REVIEW

**Comment by confused-Techie** [comment]
So finally having the chance to review this properly, overall it looks fantastic and great work!

Works flawlessly and gives a very nearly same experience for most simple documents.

There is only one change that I found a bit odd at first, but if this is intentional, feel free to ignore.

But the `#` of a heading was coloured differently than the rest of the text within a heading. It feels weird that these are coloured differently than each other, I've taken a screen shot, with the scope at the cursor visible, keeping in mind the cursor is at the end of the heading text, if you've got any ideas there I'd be happy to hear what you think.

image

**Comment by savetheclocktower** [comment]
I thought I fixed that. I'll take a look.

**Comment by savetheclocktower** [comment]
Addressed the heading punctuation color thing.

I'm trying to get the CI green just for safety's sake, but keep in mind that it was all green before I pushed a CSS fix that couldn't possibly be the cause of new test failures.

**Review by confused-Techie — APPROVED** [review]
LGTM! Thanks for addressing that issue, lets get it merged in time for the next release

**Pull request merged**
