### PR TITLE
[language-clojure] Stop detecting `.org` files as `language-clojure`

### LINKED ISSUE #934: Org files are detected automatically as Clojure scripts
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Organized files (.org files) are detected by Pulsar Editor as Clojure files, causing many different problems (e.g., related to highlighting and slowness). This seems to happen with any version later than 1.112.1. Files with extension .org should be detected as "Organized" files. I can change this manually by selecting the suitable option in the status bar, but when I open the file again I need to change it again every time. The problem is that if I open a large .org file (which is usually the case in my system), Pulsar freezes for quite a long time because it tries to interpret it as Clojure.

The solution to this problem seems to be extremely simple (just interpret .org files as "Organized" rather than "Clojure" files), but it made me go back to version 1.112.1 (as otherwise it is unusable for me due to the "freeze effect" mentioned).

### Pulsar version

1.114.0

### Which OS does this happen on?

🍎 macOS

### OS details

Sonoma

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

Just try to open an organized file with extension .org. You will see in Pulsar's status bar that it is recognized as a Clojure file instead. You can change it manually to solve temporarily the problem, but you will have to do this every time.

### Additional Information:

_No response_

### PR DESCRIPTION
**Pull request by confused-Techie**
Resolves #934 

According to Mauricio there's no case where an `.org` extension would be a Clojure file, yet the various types of clojure grammars detect it as such. 

So seems we can simply remove that extension from these lists to solve the issue.

### CODE REVIEW

**Comment by DeeDeeG** [comment]
Huh, I traced the inclusion of `.org` mode in the `language-clojure` package to this PR: https://github.com/atom/language-clojure/pull/47

In which it is acknowledged to be the "org-mode" format, same name as #934 calls them, and the atom/language-clojure package acknowledged labeling them as clojure might have some conflicts with other uses of org-mode files, but apparently some clojure-based project they link to as an example to justify it had some org-mode files checked in to their repo... Said repo has since changed its default branch to `feature/no-org` and deprectaed all their "org-mode" files...?

So, if you want to scratch your head a bunch, not being very familiar with Clojure _or_ org-mode files, this issue/PR/breadcrumb trail seems like a great opportunity to get some head-scratching in!

**Review by DeeDeeG — APPROVED** [review]
_As far as I can tell_ this seems like the right thing to do.

Not quite sure I understand why this extension was added for this language/grammar in the first place, but eh??? I understand the rationale for removing it better than the rationale for ever adding it in the first place. So, approved.

As far as I can tell from some searching around, org-mode is a plaintext markup language kind of like markdown or rst. And as far as I can tell it is not clojure.

**Comment by DeeDeeG** [comment]
Hmm, okay, sorry for all the noise, but it seems like there was a single repo where there were a lot of org-mode files that have inline code blocks of clojure... And the person's solution for that was to mark any and all org-mode files as clojure...???

If I'm understanding right, that's like saying "I know of a repo that has some markdown files with a lot of JS code blocks in it. Can we highlight every markdown file as if it were JS so those code blocks are nicely highlighted?" i.e. totally not the right way to do this.

If anything it should have been set up as one of those things where an org-mode file can have a segment detected as a block of clojure and switch to highlighting as clojure _only inside of the code block,_ then resume highlighting as org-mode outside of the code blocks. ... Right? I think so.

**Comment by confused-Techie** [comment]
Wow @DeeDeeG thanks for tracking this down, but that truly seems like such a bizarre choice to have been allowed as a commit. So seems like absolutely the best thing to do is remove this, especially since the originally justification no longer exists.

Thanks for the review, I'll go ahead and merge this one

**Pull request merged**
