### PR TITLE
Removing deprecated usage of `moveItemToTrash`

### PR DESCRIPTION
**Pull request by mauricioszabo**

### CODE REVIEW

**Review by savetheclocktower — COMMENTED** [review]
Whoops — I made this change, but I think I overwrote it when I merged from `master` — the backport revert commit must've done it. Does this just undo that commit? If so, 👍 — otherwise I'm happy to re-apply the original fix.

**Comment by mauricioszabo** [comment]
It's not the same - I looked at your original commit and indeed my code is very different.

Let me test locally here, tomorrow, before we decide to merge :)

**Comment by savetheclocktower** [comment]
Oof, `tree-view-package-spec.js` has been fucked since I merged from 1.122. I don't know how I missed that. Let me clean this up myself.

**Comment by savetheclocktower** [comment]
OK, I pushed the _status quo ante_ to `updated-latest-electron`; if I did it right, this PR should no longer be necessary.

There are spec failures on `tree-view` that I've got to get into at some point, but fewer of them seem to fail when I run the specs now (compared to when I run the specs against the commit before the one where I committed merge conflicts to the tree view specs).

That should make this PR unnecessary, so I'm going to close it. Thanks for noticing this regression.

**Pull request closed without merging**
