### PR TITLE
add or update `packages/*/package-lock.json`

### PR DESCRIPTION
**Pull request by Sertonix**
This updates or adds the `packages/*/package-lock.json` files.
This is to achieve consistent builds even if single packages are build. And also is a lot more consistent than before.

### CODE REVIEW

**Comment by CatPerson136** [comment]
Ok cool hopefully this will help me run it using yarn

**Comment by Sertonix** [comment]
> Ok cool hopefully this will help me run it using yarn

I don't think this will help, sorry. This should not effect the main build.

**Comment by confused-Techie** [comment]
So on this, I'm not sure this will have the effect intended. The main editor should always be built with using `yarn` which will be ignored in this instance. The bundled packages would then also be built with `yarn` when the editor is built.

I may recommend that if you wanted to improve the consistency of builds for our bundled packages would be instead to remove all the `npm` lock files and replace with `yarn` but even then, I'm not sure if that has an effect or if those deps are then hoisted to the main editor lock file. Which the latter is what I believe is happening

**Comment by Sertonix** [comment]
Since ppm is using npm internally these lock files would be used if these packages are installed directly. So I would say a npm lock file makes more sense.

**Review by confused-Techie — APPROVED** [review]
As confirmed on our Discord, included these may make builds easier in an edge case, but valid usage non-the-less.

Specifically if a user where to install one of our bundled packages using `ppm` when pointing at a local copy, then these lock files could be of assistance. Since `ppm` uses `npm` for installation.

Otherwise when building the editor, they will just be ignored, and we can ensure that we write additional exclusions for these files.

But in that case this looks great to me, and would be fine with merging.

**Pull request merged**
