### PR TITLE
[status-bar & tree-view] Manual Decaf Source

### LINKED ISSUE #444: Finish Decaffing all core packages
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Like the title says, we want to continue to decaf all core packages, and any help here is gladly appreciated!

For a quick reminder here's the basic workflow we would want to see during a decaf PR.
1) Get a branch made on this repo, of `<package>-decaf` (may need to contact the admins here, which can be done via issues or on Discord). This branch will **only** contain the machine decaf files. That's all, nothing deleted or modified from the machine decaf code.
2) Then fork this branch specifically, and make your manual decaf changes as needed. To help make the code look nice, and match modern JavaScript standards.
3) Once done create a PR of your changes to the `<package>-decaf` branch.
4) If the review goes well then your changes can be merged directly to the `master` branch and we are good to go!

Again some quick important notes:
* The `<package>-decaf` branch can **only** contain machine decaf code. Nothing else, no other changes
* Your manual decaf work should be properly limited in scope, a decaf PR is not the time for additional refactoring or features, it'll be easier to review and merge, if it's scope stays to decaf work, additional PRs for other changes can always be made after or before hand.
* Lastly, make sure to only decaf either the `specs` or `lib/src` files in a package at a single time. These should not be decaffed together

With all of that said, below will be a list of core packages on this repo that still need to be decaffed.

* [x] `autocomplete-css` Source
* [x] `autocomplete-css` Specs
* [x] `autocomplete-atom-api` Source
* [x] `autocomplete-atom-api` Specs
* [x] `autoflow` Source
* [x] `autoflow` Specs
* [x] `deprecation-cop` Source
* [x] `deprecation-cop` Specs
* [ ] `tree-view` Source
* [x] `tree-view` Specs
* [x] `language-c` Specs
* [x] `language-clojure` Specs
* [x] `language-coffee-script` Specs
* [x] `language-csharp` Specs
* [x] `language-css` Specs 
* [x] `language-gfm` Specs
* [x] `language-git` Specs
* [x] `language-go` Specs
* [x] `language-html` Specs
* [x] `language-hyperlink` Specs
* [x] `language-java` Specs
* [x] `language-javascript` Specs
* [x] `language-json` Specs
* [x] `language-less` Specs
* [x] `language-make` Specs
* [x] `language-mustache` Specs
* [x] `language-objective-c` Specs
* [x] `language-perl` Specs
* [x] `language-php` Specs
* [x] `language-python` Specs
* [x] `language-ruby` Specs
* [x] `language-ruby-on-rails` Specs
* [x] `language-sass` Specs
* [x] `language-shellscript` Specs
* [x] `language-sql` Specs
* [x] `language-text` Specs
* [x] `language-todo` Specs
* [x] `language-toml` Specs
* [x] `language-xml` Specs
* [x] `language-yaml` Specs
* [x] `settings-view` Source
* [x] `settings-view` Specs
* [ ] `status-bar` Source
* [x] `status-bar` Specs
* [X] `wrap-guide` Source
* [x] `wrap-guide` Specs

### What benefits does this feature provide?

Code that everyone is happy to work with, and comfortable with.

### Any alternatives?

Leave the code as CoffeeScript, and have to half learn it every time it needs changes.

### Other examples:

Would highly recommend looking at #443 for a newer example of this
Additional examples of this workflow and the changes we would want to see on decaf work can be seen here:
* #357 
* #352

### PR DESCRIPTION
**Pull request by confused-Techie**
Alright, here's the long awaited **last** decaf PR for the foreseeable future.

In this PR I've gone ahead and decaffed the `source` of:

* `status-bar`
* `tree-view`

But it feels important to mention the decaf here is light, partly because that's why most decaf PRs have gone so smoothly, but this light work is especially present in `tree-view/lib/tree-view.js`. This file is `1,593` lines long, with some complex logic behind it. And rather than attempt significant decaf work, which 1. I feel would have to warrant a thorough review of this code and 2. has a very likely chance of causing breaking changes in this section of the codebase, I've instead opted to leave it nearly untouched, even so far as leaving behind the decaffination tips, for whoever in the future plans to refactor this file, which is severely needed, but as such a PR would have a significantly smaller scope, it feels much more achievable there, than it does here.

(So if someone in the future, is using git blame to find out why this file is such a mess, sorry about that)

---

Otherwise this PR is just like all other decaf work, the diff will temporarily be using the base branch `machine-decaf-source` until such a time as all tests are passing, and hopefully with a review, then the branch will be changed to `master` making the diff unreadable.

Resolves #444

### CODE REVIEW

**Comment by confused-Techie** [comment]
So in the body of the PR I've described how much of a complex mess `tree-view.coffee` was, and that I did very little decaf work at risk of breaking things.

It seems we found one of the few files where it truly matters the exact version of CoffeeScript is being used. That means I had to redecaf `tree-view.coffee` using **exactly** CoffeeScript 1.12.7 (The version Pulsar uses currently internally during runtime) or else the package would break.

This unfortunately means that the file has become even less readable as a result, and now at it's `2,049` line long self, I'm even more inclined to leave this cleanup to a future refactor, one where this file is essentially the only purpose of the PR, otherwise testing and diffs become nearly impossible to fully understand.

All I've done to this file is add back in comments, and that's it. (Since this version of CoffeeScript drops comments entirely)

**Comment by confused-Techie** [comment]
Alright, as we have done with all other decaf PRs, tests here are happy, I'll go ahead and change the main branch over.

**Comment by confused-Techie** [comment]
Alright, with happy tests, gonna go ahead and merge this one!

**Comment by DeeDeeG** [comment]
👍 on this PR in general, as per all the decaf PR's generally, but:

I think this upset the "documentation" GitHub Actions workflow.
https://github.com/pulsar-edit/pulsar/actions/runs/6117983762/job/16605413592

Just noting it, I can try and help fixing it once I get some other things out of the way, backlog items, etc.

**Comment by confused-Techie** [comment]
@DeeDeeG Good catch on that, yeah I didn't notice.

I believe this stems from `tree-view.js` Line 1734. Where we turned the following comment:

```coffeescript
  # Public: Return an array of paths from all selected items
  #
  # Example: @selectedPaths()
  # => ['selected/path/one', 'selected/path/two', 'selected/path/three']
  # Returns Array of selected item paths
```

Into:

```javascript
  /**
     * @memberof TreeView
     * @function selectedPaths
     * @desc Public: Return an array of paths from all selected items
     * @example
     * @selectedPaths() => ['selected/path/one', 'selected/path/two', 'selected/path/three' ]
     * @returns {array} Selected item paths
     */
```

And if I had to guess, while this is valid, and attempts to represent the same exact comment, since the comment comes from `coffeescript` where the `@` within the code meant to reference `this` using that same exact comment below the line `@example` makes JSDoc think we are instead attempting to declare another tag. So we should probably fix this to change the line below `@example` to:

```javascript
/** 
* this.selectedPaths() => ['selected/path/on', 'selected/path/two', 'selected/path/three']
*/
```

And that will likely resolve the error.

**Pull request merged**
