### PR TITLE
Isolate and Modernize Dependencies

### PR DESCRIPTION
**Pull request by confused-Techie**
# No Longer Blocked 

Initially this PR was blocked because the dependency `fs-plus` was using a prepublish script to decaffienate and prepare their code. Originally the idea was to remove it's usage from this repo and potentially merge. But reviewing further this was not the only dependency to do this, and progress on removing will take it's time.

So instead lets go ahead and look at merging this PR now considering.

## Modules that use `prepublish` scripts to prepare code and cannot be directly linked:

* fs-plus
* scoped-property-store
* nslog

---

This PR aims to help us get control of the many dependencies on the editor.

This is accomplished by doing several different things. 

* Updated some modules to a changed name, leaving at the same version.
* Standardizing the method used to import a local file as a package. (By choosing the more popular one within our codebase)
* Moved all `codeload` modules to our own repositories.
* Moving all Atom published NPM modules to our own `codeload` repositories.

With all of this done there are some items that could not be accomplished, or may need further attention in the future.

---

## Modules currently Published/Hosted by Atom-Community

* `babel-preset-atomic`
* `find-and-replace`
* `snippets`

---

## Modules that are published by Atom on NPM, but have a version mismatch to what's available in GitHub.

* `atom-select-list`: Uses: 0.8.1 - GitHub has up to: 0.7.2
* `etch`: Uses: 0.14.1 - GitHub has up to: 0.14.0
* `first-mate`: Uses: 7.4.3 - GitHub has up to: 7.4.2
* `git-utils`: Uses: 5.7.1 - GitHub has up to: 5.7.0
* `superstring`: Uses: 2.4.4 - GitHub has up to: 2.4.3
* `text-buffer`: Uses: 13.18.6 - GitHub has up to: 13.18.3

---

Beyond this a quick note, is that any dependencies that were not locked, and have been moved to locked `codeload` versions have been moved to most up to date version that would've been selected by NPM based on the semver.

### CODE REVIEW

**Comment by confused-Techie** [comment]
This PR is no longer blocked and is now ready for review. 

Due to changes since it was created had to rebase and fix some items that were removed during conflict resolution.

Otherwise, these updates have been tested to ensure they work locally, and do what the original PR aimed to accomplish. If anyone is able to take a look that is greatly appreciated.

**Comment by Sertonix** [comment]
Could it be that this is not up to date with the ppm master branch? Since it shows that the `ISSUE_TEMPLATE.md` is added again [here](https://github.com/pulsar-edit/pulsar/pull/100/files#diff-616c1af8cc7f4556975b7cbe50bce072e87a5e5c4c14b3ccb87575fc547b3167)

**Comment by confused-Techie** [comment]
> Could it be that this is not up to date with the ppm master branch? Since it shows that the `ISSUE_TEMPLATE.md` is added again [here](https://github.com/pulsar-edit/pulsar/pull/100/files#diff-616c1af8cc7f4556975b7cbe50bce072e87a5e5c4c14b3ccb87575fc547b3167)

Yeah you have a point. How weird, since in my PR I don't touch `ppm` other than when I had to rebase. Strange, I'll take a look at it, but may be simplier to start fresh off of the current master. Let me see

**Comment by confused-Techie** [comment]
Since this PR is significantly out of date, I'll go ahead and close this, and redo it on the current master branch.

**Pull request closed without merging**
