### PR TITLE
remove package.json dependencies

### PR DESCRIPTION
**Pull request by Sertonix**
This removes a few dependencies from the `package.json` that are not used in the core. Also this removes the config of the `standard` linter since it is not used.

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
This looks great to me! Interesting we have so many dependencies that aren't in use anywhere. But just want to check in real fast was anyone from @pulsar-edit/core using these for any purpose? Or do you think they will interfere with any active work you are doing? Otherwise this looks great and lets merge

**Review by DeeDeeG — APPROVED** [review]
App seems to work from the Cirrus binary (Linux x64 .deb, Ubuntu 22.04). :heavy_check_mark: 

I have some basic familiarity with some of these packages, and beyond that, from running `git grep --name-only [package_name_here]` and various `git blame` commands I can gather:

- @atom/fuzzy-native - The package is not apparently used at top-level in the repo. Looks like this was a way to pin a newer version for (ultimately for the `fuzzy-finder` dependency to use) during the Electron 9 upgrade and stayed there ever since. [\[1\]](https://github.com/atom/atom/commit/f4d832f2e2e45eff20bfb17a8e1244db3a90636d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17) --> [\[2\]](https://github.com/atom/atom/commit/662c0c43875d94e21d82e9a9b294a04b5141bddb)
  - As long as our dependencies end up on `@atom/fuzzy-native` 1.2.1 or later [\[3\]](https://github.com/atom/atom/commit/0a8684575d96648d871c5db38788e419e3b1791b), we're good. Looks like that is the case. (There is no newer version to get, so... Yeah. We're good.)
  - There is (and was) no real reason why this had to be in the main `package.json`, other than to prevent package managers from downgrading the lockfile/ other shenanigans when doing package updates??? But this shouldn't be a thing, and we trust our packages to define their own dependencies generally, so... Yeah, I think this was a bit of weird/convenience-oriented package bumping practices in the upstream project.
  - If they wanted this update done super properly, with a new minimum version that can't be messed up by sneaky changes to the lockfile, they could have bumped `@atom/fuzzy-native` in the `fuzzy-finder` package, then pulled in the new `fuzzy-finder`. But I suppose this was the quick and convenient way to get the version updated in Atom with the npm CLI.
- devtron - I happen to know this is a thing you could load to get some insights to the Electron app. An Electron-specific panel for the Dev Tools. But it's super old and unmaintained/not updated for some time now, and I think it broke at some point a while ago with newer Electron versions. You can attempt to load it in the dev tools of Pulsar if you are curious. But I think we can safely remove it, because parts of it are rather broken, and most people don't know it exists.
  - https://github.com/electron-userland/devtron
- electron-notarize, electron-osx-sign - Not apparently used in Pulsar. Were used by the signing steps of the old build scripts, but they're not actually useful if you don't have (generally paid) signing certificates for the Windows or macOS platforms.
- prebuild-install - Not obviously used anywhere in our files. I think individual packages are supposed to depend on this and define a `build` script in their `package.json` to run this. So, I'm not sure why it's in Atom's/Pulsar's main `package.json`.
  - More indirect dependency bumping / strange / convenience-oriented package bump practices at upstream? https://github.com/atom/atom/commit/2a9c63d5b78 (once again during an Electron bump)

**Comment by DeeDeeG** [comment]
The merge conflict with `script/package.json` could be avoided if we drop the two commits from the beginning of the branch.

(The commits which pruned stuff from `script/package.json`, and then reverted those changes, respectively).

I'd be willing to rebase this branch real quick if we have push permissions to the PR branch at @Sertonix's fork. Otherwise @Sertonix you can do the rebase (as long as this makes no diff to the files I'll accept the previous approvals.) Or we can manage the merge on our end, manually on the CLI.

**Comment by Sertonix** [comment]
@DeeDeeG it would be nice if you do that.

**Pull request merged**
