### PR TITLE
Disable and/or fixing failing tests

### PR DESCRIPTION
**Pull request by mauricioszabo**
Over discord, we discussed how should we handle editor tests that are failing.

This PR fixes the tests that are fixable, and disables the others that are flaky, are indeed failures, or that we really don't understand what they are so we can get a better view on when the editor _actually works_ and when our work doesn't break any new thing

### CODE REVIEW

**Comment by fabianfiorotto** [comment]
@mauricioszabo  if you disable these tests in `spec/buffered-process-spec.js` 
```js
it('doesnt start unless start method is called', function() {}
it('calls the specified stdout, stderr, and exit callbacks', function() {}
```

then all tests in `spec/workspace-element-spec.js` pass. You don't have to disable them.

**Comment by confused-Techie** [comment]
> @mauricioszabo if you disable these tests in `spec/buffered-process-spec.js`
> 
> ```js
> it('doesnt start unless start method is called', function() {}
> it('calls the specified stdout, stderr, and exit callbacks', function() {}
> ```
> 
> then all tests in `spec/workspace-element-spec.js` pass. You don't have to disable them.

To add onto this with the changes on my PR #42 fixing `spec/buffered-process-spec.js` the tests in `spec/workspace-element-spec.js` work just fine now.

So if that is merged, then at least these two tests won't have to be disabled

**Comment by confused-Techie** [comment]
I've cherry picked the commits from this branch in PR #48 and have merged that to main. This is still a great resource to see some of the tests that are failing, but that PR took the commits that fix tests, and they are now available on master.

**Comment by kaosine** [comment]
I wonder if, with this one, that we should update it to the commits it's missing with main? That way we could figure out which ones are still failing, disable them and work on them one by one. That way, it's less daunting of a task to re-enable them once they're fixed/rewritten?

**Comment by confused-Techie** [comment]
Considering that we now have tests passing in general, seems it may be time to close this PR.

An example of having all tests passing can be seen [on a recent GitHub Action for a PR that doesn't touch tests](https://github.com/pulsar-edit/pulsar/actions/runs/3344862008/jobs/5539705127). 

Now while we still have some tests that can fail in different environments, I'm not sure that this would be the most effective at addressing those issues. 

So unless we feel that doing this would still be the best way we can reopen it, otherwise I'll go ahead and close for now.

**Pull request closed without merging**
