### PR TITLE
Using "second-mate"

### PR DESCRIPTION
**Pull request by mauricioszabo**
Second-mate is basically the Atom's "First Mate" (TextMate helpers) but converted to use `vscode-oniguruma` instead of `node-oniguruma`.

This PR adds support for second-mate as the TextMate tokenizer. For related PRs, see here: https://github.com/pulsar-edit/second-mate/pull/1

We may need more tests on this code, and also fix bracket-matcher (that it needs first-mate - maybe even use Pulsar's tokenizer instead)

### CODE REVIEW

**Comment by confused-Techie** [comment]
Excited to see how the tests turns out on this one

**Comment by savetheclocktower** [comment]
I should've mentioned this on the `second-mate` repo, but: if we can replicate the `OnigRegExp` API with only `OnigScanner`, it'd be great if we could do that in `second-mate` and export both `OnigRegExp` and `OnigScanner` from `second-mate` itself — just to prevent having to rewrite all these usages.

**Comment by mauricioszabo** [comment]
@savetheclocktower yeah, that's a good idea...

Unfortunate, it's too late now :laughing:

**Comment by mauricioszabo** [comment]
I _honestly didn't like_ the errors the CI reported...

**Pull request merged**
