### PR TITLE
Bundle notifications

### PR DESCRIPTION
**Pull request by mauricioszabo**
Also, rebrand to Pulsar, and fix quite a lot of issues on opening issue, finding issues on GitHub, etc.

* [`notifications#1 - Cleanup and rename @Sertonix `](https://github.com/pulsar-edit/notifications/pull/1)
* [`notifcations#2 - reject promise with Error instance @Sertonix `](https://github.com/pulsar-edit/notifications/pull/2)
* [`notifications#3 - Add our Testing Action @confused-Techie `](https://github.com/pulsar-edit/notifications/pull/3)
* [`notifications#4 - Change atom strings to pulsar @mdibella-dev `](https://github.com/pulsar-edit/notifications/pull/4)
* [`notifications#5 - Bump to v3.2 of action-pulsar-dependency @confused-Techie `](https://github.com/pulsar-edit/notifications/pull/5)
* [`notifications#6 - Fix all Tests @confused-Techie `](https://github.com/pulsar-edit/notifications/pull/6)

### CODE REVIEW

**Comment by confused-Techie** [comment]
@mauricioszabo Can you do me a favour and add the below text into the body of your PR? It'll make things a whole lot easier when writing the ChangeLog later

---

```
* [`notifications#1 - Cleanup and rename @Sertonix `](https://github.com/pulsar-edit/notifications/pull/1)
* [`notifcations#2 - reject promise with Error instance @Sertonix `](https://github.com/pulsar-edit/notifications/pull/2)
* [`notifications#3 - Add our Testing Action @confused-Techie `](https://github.com/pulsar-edit/notifications/pull/3)
* [`notifications#4 - Change atom strings to pulsar @mdibella-dev `](https://github.com/pulsar-edit/notifications/pull/4)
* [`notifications#5 - Bump to v3.2 of action-pulsar-dependency @confused-Techie `](https://github.com/pulsar-edit/notifications/pull/5)
* [`notifications#6 - Fix all Tests @confused-Techie `](https://github.com/pulsar-edit/notifications/pull/6)

Resolves #347 
```

**Review by confused-Techie — APPROVED** [review]
Assuming the `notification` tests all pass, fully approve.
I've tried this once before and got stumped, so super excited to see it working now!

**Comment by mauricioszabo** [comment]
@confused-Techie  Oh.... wait a little bit....

I think I didn't merge the changes from our notification package :facepalm:

**Comment by mauricioszabo** [comment]
Ok, done - authored the only code change on the latest commit /cc @Sertonix and @confused-Techie

**Comment by confused-Techie** [comment]
Awesome thanks @mauricioszabo 

Also lets see if this adds it to the PR properly.

Resolves #347

**Comment by Sertonix** [comment]
I forgot to check the files when it was open. My cleanup and rename pull request doesn't seem to be included eather.
Are you sure the other pull requests are?

**Pull request merged**
