### PR TITLE
deps: Update electron-builder to 24.6.5

### PR DESCRIPTION
**Pull request by DeeDeeG**
### Identify the Bug

Pulsar's macOS binaries from GitHub Actions are either not signed, or signed in such a way that the Gatekeeper popup shows:

> “Pulsar” cannot be opened because the developer cannot be verified.

This PR is trying something as a bit of a long shot that _might_ address the "not properly signed" scenario. (The "completely unsigned" scenario is due to an issue with the workflow file, and appears to be a separate issue.)

### Description of the Change

Bump our electron-builder dependency to 24.6.3.

Maybe this will fix macOS signing/notarizing in GitHub Actions???

Need to run a PR and see if it works to find out, since this is, for our intents and purposes, currently a CI-only issue.

### Alternate Designs

This is just a check-and-see "maybe fix". No specific alternatives were considered, besides perhaps locally trying to reproduce the "signing/notarizing didn't work" issue. That remains an option.

### Possible Drawbacks

See the release notes, I haven't read through them exhaustively, but nothing particularly stood out to me...

https://github.com/electron-userland/electron-builder/releases

I chose the latest one not marked "Pre-Release", so this should be a relatively stable and well-tested version, I hope?

### Verification Process

- [ ] CI should pass.
- [ ] Downloaded macOS assets from this PR's GitHub Actions "build Pulsar binaries" workflow should be fully properly signed. They should open without presenting the "cannot be verified" popup.

### Release Notes

(Tentative, pending testing): "Fixed app signing for macOS in GitHub Actions CI"

### CODE REVIEW

**Comment by DeeDeeG** [comment]
_Ze dependency bumps, zey do nossing!_

**Comment by JonathanDoughty** [comment]
Given the information on [mastodon](https://infosec.exchange/@TomSellers/111126339492371432) and [Ars Technica](https://arstechnica.com/security/2023/09/incomplete-disclosures-by-apple-and-google-create-huge-blindspot-for-0-day-hunters/) you might want to target Electron v24.8.3 or later

**Comment by DeeDeeG** [comment]
@JonathanDoughty I've seen that info, and yeah, it affects Pulsar, unfortunately.

Getting the editor on newer versions of Electron was a main focus around Atom toward the end, even since before we forked from it to make Pulsar, and likewise since forking it's something we in pulsar-edit org want to do as soon as we feasibly can. And we do have efforts taking place to jump to the very latest Electron version. There's been discussion on our Discord server of putting a beta version out that does that, brought up again in the past few days, but it's been a big effort that's been built toward for a long time. (Credit mostly to @mauricioszabo for these efforts so far.) I wouldn't commit to any specific timeline other than "as soon as we can make sure it doesn't break (a lot of) things."

We are unfortunately still on Electron 12 at the time I'm writing this. And of course we want to get on a newer version as soon as feasible, for security reasons.

**Comment by DeeDeeG** [comment]
I'm closing this PR, since this was meant to update our _build tools_ and fix code signing, not bump the Electron version (that could be posted as a separate issue).

I don't mind at all if there's an issue or Discussion opened about the Electron version being out of date, if anyone wants there to be such a dedicated issue or Discussion.

(This PR isn't needed anymore since #743 took care of the code signing situation. I'd like to close this one to clean up the open PRs list.)

**Pull request closed without merging**
