### PR TITLE
add allow-jit entitlement (fixes Apple Silicon builds)

### PR DESCRIPTION
**Pull request by Meadowsys**
Apple Silicon macOS builds have been broken since the introduction of `second-mate`. This is because loading the wasm of `vscode-oniguruma` fails. As stated in [this comment](https://github.com/electron/electron/issues/27497#issuecomment-776454100), enabling the `com.apple.security.cs.allow-jit` entitlement would fix the issue, and it has. I can imagine a not insignificant amount of wasm packages, so if this would be a problem for those, this PR would fix them as well.

### CODE REVIEW

**Review by confused-Techie — COMMENTED** [review]
Super impressive find here, fingers crossed this works as we hope!

**Comment by Meadowsys** [comment]
Might need a few more Apple Silicon users to confirm (test master, test this one), but I have tested it myself using a commit build ([on this run], [direct dmg download link]) and it does seem to fix the issue >w<

[on this run]: https://cirrus-ci.com/task/4710650522370048
[direct dmg download link]: https://api.cirrus-ci.com/v1/artifact/task/4710650522370048/binary/binaries/Pulsar-1.103.2023040222-arm64.dmg

**Comment by mauricioszabo** [comment]
@Meadowsys can I, or you, merge back `master` on this? `master` is now running the visual tests using the MacOS binaries that we generated, so if Cirrus pass we can say that this issue is fixed :)

**Comment by Meadowsys** [comment]
sure @mauricioszabo you can do it c:

**Comment by mauricioszabo** [comment]
@Meadowsys done, let's see if CI works :)

**Comment by mauricioszabo** [comment]
@Meadowsys here's a timeline:
1. I merged back master to it, and every build failed
2. We found that master was also failing on every build, so we went to investigate and found that i18n feature was responsible to breaking builds, so we reverted it
3. I merged back master to this branch;
4. Finally, we now are back to green here - full green, including Silicon.

So, can we merge this one?

**Comment by Meadowsys** [comment]
Sounds good, I can merge it

**Pull request merged**
