### PR TITLE
Bundle `autocomplete-plus`

### PR DESCRIPTION
**Pull request by confused-Techie**
This PR follows all previous guidelines on the topic. 

* Adds and updates a `package-lock.json`
* Removes the MIT license file as it matches the repo license
* Rebrands the `README.md` and `package.json`

Otherwise this PR bundles `autocomplete-plus` updating the pulsar `package.json` and `yarn.lock`

### CODE REVIEW

**Comment by confused-Techie** [comment]
FYI: Seems an error was made when bundling and the incorrect commit SHA was used, missing some of the changes available on the tagged ref we were previously using. So this bundled `autocomplete-plus` is still using the outdated Atom Jasmine3 test runner. This will be resolved, but until then should not be merged since while tests pass locally, they do not pass in Ci

**Comment by confused-Techie** [comment]
Alright, sorry about the temporary error.

This PR is now good to review with:

* find-and-replace: 66 Failures (We expect 51  ± ~10 so this seems to fall into the expected range)
* symbols-view: 2 Failures (We expect 2)
* tree-view: 2 Failures (We expect 2)

So the tests are right where we would expect them, other than `find-and-replace` being a slight range that is hard to predict. So essentially this PR should be good to go.

**Review by DeeDeeG — APPROVED** [review]
I can confirm this 100% matches the previously specified 1f056ef commit of our fork of `autocomplete-plus` (see this branch https://github.com/pulsar-edit/autocomplete-plus/tree/fix-outdated-test-lib)...

Other than in README.md deleting an obsolete Travis CI badge and rebranding an instance of "Atom" to "Pulsar", which makes sense to me.

Approved!

**Comment by confused-Techie** [comment]
@DeeDeeG Thanks again for your review! I appreciate your time and effort! I'll resolve the conflicts on this one and get it merged!

**Pull request merged**
